### ISSUE TITLE
autologon fails using 32-bit powershell, succeeds on 64-bit

### ISSUE THREAD

**Issue by mwrock** [chocolatey/boxstarter#1]
From https://boxstarter.codeplex.com/workitem/87/edit

Here's a simple Boxstarter script I'm using to test autologin.  I save this to my desktop as test.ps1.

```
if ( Get-UAC )
{
    Disable-UAC
    Invoke-Reboot
}
```

And here's the code I'm using to run the boxstarter script

```
Set-ExecutionPolicy Unrestricted -Force
iex ( ( new-object net.webclient ).DownloadString( 'https://chocolatey.org/install.ps1' ) )
cinst Boxstarter
boxstartershell
$creds = Get-Credential
Install-BoxstarterPackage -PackageName "c:\users\YOUR_USER\desktop\test.ps1" -Credential $creds
```

I'm running this from a clean 64-bit Win 7 SP1 machine with all windows updates already applied.

When I run this using 64-bit Powershell there are no issues.  The machine reboots, the auto-login occurs, and boxstarter finishes.

However, when I run this using 32-bit Powershell ("Windows Powershell (x86)"), the machine reboots and then sits at the login screen.  I've double-checked that I'm supplying the correct username/password to Get-Credential.

**Comment by it-praktyk** [comment]
Could you considered the solution like this: http://stackoverflow.com/a/19381092 ?

**Comment by mwrock** [comment]
yeah that may work

**Comment by gep13** [comment]
Based on a discussion with @pauby I have removed this issue from the 3.1.0 milestone, and assigned the `Not Implementing` label.  Boxstarter is not intended to be run from a 32-bit session when on a 64-bit operating system, therefore we are not going to make any changes here.

A [PR](https://github.com/chocolatey/boxstarter/pull/542) has been raised to make this clear in the documentation.
