### ISSUE TITLE
Boxstarter download speed

### ISSUE THREAD

**Issue by Redsandro** [chocolatey/boxstarter#119]
The initial download of the Boxstarter package (new installation) is really slow. I'm on 200 mbit, and it still takes 20 seconds at 24 kbyte/s. There is a bottleneck. It's usually slowish, but now it seems especially slow.

Any idea why this download is slow?
Can you provide some insight in the amount of bandwidth people downloading the installer generates?
Is this huge or would it be doable/feasible for people with some spare bandwidth to co-host the file?
Is the download slow for everyone or here in the Netherlands?

Possibly related: https://github.com/mwrock/boxstarter/issues/30

**Comment by mwrock** [comment]
Its hosted on Azurewebsites out of US West. The site just serves the docs and the one-click download. Looking at recent activity it looks pretty tame. You might try checking the azure status page if things seem super slow.

**Comment by Redsandro** [comment]
Strange. Everything is okay. https://azure.microsoft.com/nl-nl/status/

I would like to turn this 20 second download into a 1 second download. But Azure cannot be the problem if they are truly starting from [165MB](https://azure.microsoft.com/nl-nl/documentation/articles/azure-subscription-service-limits/#app-service-limits) bandwidth up.
