### ISSUE TITLE
Failed to install the boxstarter

### ISSUE THREAD

**Issue by woshichuanqilz** [chocolatey/boxstarter#129]
the error msg I get is : 

Boxstarter not installed. An error occurred during installation:
The remote name could not be resolved: 'packages.chocolatey.org'
The install of Boxstarter was NOT successful.
Boxstarter not installed. An error occurred during installation:
The remote name could not be resolved: 'packages.chocolatey.org'

**Comment by mwrock** [comment]
Interesting. This is the endpoint that hosts chocolatey packages. Seems like your system may be having DNS resolution issues. You might try it again later. Are you able to ping the name and resolve to an IP?
