### ISSUE TITLE
Trying to install chocolatey with boxstarter generates error

### ISSUE THREAD

**Issue by tirolo** [chocolatey/boxstarter#147]
Based on: https://github.com/chocolatey/choco/issues/500

In short, steps to reproduce:
run `http://boxstarter.org/package/chocolatey,powershell` 

Actual: It fails to install the `powershell` package.
Expected: It should works just as running `http://boxstarter.org/package/powershell` 

Haven't tested with other packages but I have a great feeling that it will fail for any package after chocolatey.

Log:
http://screencast.com/t/is8rvAlSP

More logs:
https://gist.github.com/tirolo/48968f031172aaed931b

**Comment by mwrock** [comment]
please see my comments at https://github.com/chocolatey/choco/issues/500#issuecomment-178503246

**Comment by pauby** [comment]
Given the [comments](https://github.com/chocolatey/boxstarter/issues/147#issuecomment-178503463), closing this. If we feel this should be revisted then will reopen.
