### ISSUE TITLE
Chocolatey aborting shutdown causes Boxstarter to report failed install

### ISSUE THREAD

**Issue by sevenzsu** [chocolatey/boxstarter#148]
I am using boxstarter.org\package\url?c:\myscript.ps1 to run the script and after the package is installed successfully, boxstarter report exit code 1 in the log as below. Did some google and found something here, hope this help: https://github.com/chocolatey/chocolatey/issues/387

```
Chocolatey installed 1/1 package(s). 0 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
  The install of msbuild.communitytasks was successful.
 Chocolatey installed 1/1 package(s). 0 package(s) failed.
[2016-01-28T15:02:11.3840953-05:00:::PID 3176] Boxstarter: restoring current directory location to C:\Users\my.name\AppData\Local\Apps\2.0\XC8NK5GZ.L63\6O7WKR61.DR3\boxs..tion_4b037e62ccd024b7_0002.0006_d4dfbce912b5d99f\boxstarter.chocolatey\chocolatey
[2016-01-28T15:02:11.3840953-05:00:::PID 3176] Boxstarter: Exit Code: 1
 chocolatey : Chocolatey reported an unsuccessful exit code of 1. See C:\Users\m
[2016-01-28T15:02:11.3840953-05:00:::PID 3176] + Boxstarter finished Calling Chocolatey to install msbuild.communitytasks. This may take several minutes to complete... 00:00:14.0598503
 y.name\AppData\Local\Boxstarter\boxstarter.log for details.
[2016-01-28T15:02:11.3840953-05:00:::PID 3176] + Boxstarter finished Calling Chocolatey to install msbuild.communitytasks. This may take several minutes to complete... 00:00:14.0598503
 At C:\Users\my.name\AppData\Local\Apps\2.0\XC8NK5GZ.L63\6O7WKR61.DR3\boxs..
 tion_4b037e62ccd024b7_0002.0006_d4dfbce912b5d99f\Boxstarter.chocolatey\Chocolat
 ey.ps1:58 char:15
-     chocolatey <<<<  Install @PSBoundParameters @args
  - CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep 
- Boxstarter finished Calling Chocolatey to install msbuild.communitytasks. This may take several minutes to complete... 00:00:14.0598503
  [2016-01-28T15:02:11.3997263-05:00:::PID 3176] Boxstarter: Installing 1 packages
  tion
  - FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio 
    n,chocolatey
```

**Comment by mwrock** [comment]
please provide a gist of the boxstarter log found at `$env:localappdata\boxstarter` Thanks!

**Comment by bill-long** [comment]
I've seen this a few times as well. Just grabbed a boxstarter.log from a user who saw this:

https://gist.github.com/bill-long/e282332d86011a03d95f

**Comment by mwrock** [comment]
Boxstarter checks the environment's exitcode immediately after running a chocolatey package. Its certainly possible to have a script that ends up with a non zero exit code even though things seemed to have gone ok. I'm certainly not saying there could be something wrong on boxstarter's end, but especially if you are seeing this happen consistently with a particular script, try printing out the `$LASTEXITCODE` variable at the end of the script. If it is not 0 then that indicates something in the script triped that code.

**Comment by bill-long** [comment]
In the gist above, the user reported that they had seen the error when they only installed Beyond Compare 4. Looking at the gist, I see that Beyond Compare 4 did indeed succeed - but after that, something runs a `shutdown /a` command. That command is what returned a nonzero exit code.

That command is not in the boxstarter script, but it looks like Chocolatey itself issues a `shutdown /a` in this file: https://github.com/chocolatey/choco/blob/4d37117c926ae02fd57e35c06355e4aca729fd7d/src/chocolatey/infrastructure.app/services/ChocolateyPackageService.cs

```
if (powerShellRan)
{
    // we don't care about the exit code
    if (config.Information.PlatformType == PlatformType.Windows) CommandExecutor.execute_static("shutdown", "/a", config.CommandExecutionTimeoutSeconds, _fileSystem.get_current_directory(), (s, e) => { }, (s, e) => { }, false, false);
}
```

Testing on my own machine, this returns the exit code we see in the gist if it is run when no shutdown is in progress:

```
C:\> shutdown /a
Unable to abort the system shutdown because no shutdown was in progress.(1116)
```

So it appears that sometimes choco will issue a shutdown abort when no shutdown is in progress. The nonzero exit code from that is what makes Boxstarter report a failure. I'm opening an issue in the choco repo.

**Comment by riezebosch** [comment]
I've got this [extensive](http://paste.ee/p/rJhbo) log where I draw the following conclusion from:

- chocolatey always invokes a shutdown /a
- for me this always results in exit code 1116 because no shutdown was scheduled
- sometimes chocolatey exits with exit code 1 for no apparent reason
- but boxstarter (or chocolatey) indicates the package install has failed
- this only happens when a reboot was indeed required

I have no workaround as of yet. Most installs are just fine after a reboot when the package is idempotent but for one package I have the workaround to install it a second time with -n to not execute the install script but still mark it as installed.

**Comment by pauby** [comment]
Keeping this open until https://github.com/chocolatey/choco/issues/610 is resolved.

**Comment by pauby** [comment]
@mwallner @flcdrg is this still an issue? I don't think I've ever come across this when using Boxstarter.

**Comment by mwallner** [comment]
I doubt that this is still relevant (especially since Boxstarter v3 looking at the given output above, the way Boxstarter used to hijack the session of choco made it probably more sensible to stderr/write-error problems than necessary).

I'd vote to close the issue and link a new one here if it ever happens again.
