### ISSUE TITLE
Installing adobereader displays Reboot Dialog

### ISSUE THREAD

**Issue by PilotBob** [chocolatey/boxstarter#149]
My boxstarter script includes cinst adobereader. 

When it goes to install adobereader a dialog is put on the screen that a reboot is needed, Yes/No. This prevents the script from running fully unattended. Is there a way to have boxstarter deal with this.

Here is my current script.

https://gist.githubusercontent.com/PilotBob/f2a1070a9f4473a47470/raw/a8ad637761bbec5d7e197e42dd03bb7a77f688a2/boxstarter.txt

I remarked out adobereader for now, so I can run this unattended.

**Comment by mwrock** [comment]
Ugh. Well boxstarter already does a pending reboot check and restarts in there is one before each package. So the reboot must be specific to adobereader. You might try asking this question in the comments section of the adobereader package.

**Comment by PilotBob** [comment]
Ah ok. So you are saying I don't need those if (Test-PendingReboot) { Invoke-Reboot }

in my script at all?

**Comment by mwrock** [comment]
Right. That should be happening under the hood before each package

**Comment by PilotBob** [comment]
thanks. I'll pull them out. I'll investigate that package issue on the choco site.

Also, is there a reason that Install-ChocolateyPinnedTaskBarItem wouldn't work? Those apps don't get pinned to my task bar. I'm running Win 10, perhaps that's why?

**Comment by PilotBob** [comment]
So, very strange... I did

http://boxstarter.org/package/adobereader 

and it installed without putting up a reboot dialog. So, I am re-running my full script again, perhaps something else is causing this?

**Comment by mwrock** [comment]
I too have noticed `Install-ChocolateyPinnedTaskBarItem` not working as of windows 10. I'm guessing there is a new way to do that. Need to investigate.

Regarding what exactly is triggering the adobereader reboot, usually the best way to troubleshoot that is to run the adobereader installer from a command line and tel it to log to a file. I'm not familiar with the adobereader installer specifically but nearly all installers I have worked with have detailed logging and often say why they are rebooting.

I'd certainly would be curious to know.

**Comment by pauby** [comment]
As this is a Chocolatey package issue for Adobe Reader I'm going to go ahead and close this as invalid. If we need to reopen it again in the future we can.
