### ISSUE TITLE
Boxstarter can't work with Basic Authenticated Proxy

### ISSUE THREAD

**Issue by igoran** [chocolatey/boxstarter#151]
Whenever I start any package from the URL of my IE (I'm within an Enterprise network with a Basic-autheticated proxy), it fails to install the Boxstarter application.

The error from the ClickOnce log is:

> Activation of http://boxstarter.org/launch/Boxstarter.WebLaunch.Application?package=sysinternals resulted in exception. Following failure messages were detected:
>       + Downloading http://boxstarter.org/launch/Boxstarter.WebLaunch.Application?package=sysinternals did not succeed.
>       + The remote server returned an error: (407) Proxy Authentication Required.

**Comment by mwrock** [comment]
hmm. There my be a way to wire things up to get click once working with a authenticating proxy, but I'm unfamiliar with those details and am a bit surprised it does not use integrated windows auth with the currently logged on user.

To get around this, you could try downloading boxstarter via chocolatey and then using the `Install-BoxstarterPackage` command.

**Comment by pauby** [comment]
As there has been no response to this in some time and the issue is at the client side I'm going to close this issue. If we need to reopen it again in the future we can do that.
