### ISSUE TITLE
An error occurred during installation:  The directory name is invalid.

### ISSUE THREAD

**Issue by sooth** [chocolatey/boxstarter#153]
I recently upgraded my Boxstarter/Chocolatey server and now am getting this message every time I attempt to install a package on another machine. I call the package installation in PowerShell like so:

```
C:..\Documents(1)> \\manage1cvg\boxshare\Boxstarter common -DisableReboots
Boxstarter: Installing package common
Boxstarter Version 2.6.25
(c) 2015 Matt Wrock. http://boxstarter.org

Boxstarter: Disabling Automatic Updates from Windows Update
++ Boxstarter starting Calling Chocolatey to install common. This may take several minutes to complete...
Installing the following packages:
common
By installing you accept licenses for the packages.

common v1.0.0 (forced)
common not installed. An error occurred during installation:
 The directory name is invalid
The install of common was NOT successful.
common not installed. An error occurred during installation:
 The directory name is invalid

Chocolatey installed 0/1 package(s). 1 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures:
- common
  Chocolatey : Chocolatey reported an unsuccessful exit code of 1. See
  C:\Users\david.malson\AppData\Local\Boxstarter\boxstarter.log for details.
  At \manage1cvg\boxshare\Boxstarter.Chocolatey\Invoke-ChocolateyBoxstarter.ps1:200 char:5
  -     Chocolatey install $bootstrapPackage -source $source -force:$forc ...
  -     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
  - FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,chocolatey

++ Boxstarter finished Calling Chocolatey to install common. This may take several minutes to complete... 00:00:09.4061
18
True
Boxstarter: Restore Automatic Updates from Windows Update
```

I am really confused. I have dug through the log and each and every command works. The content of the package is printed in the log. All the files and directories in the log exist.

**Comment by sooth** [comment]
My log: http://pastebin.com/5M0jWrPB

**Comment by mwrock** [comment]
In your log i see:
```
Calling command ['"C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -NoLogo -ExecutionPolicy Bypass -Command "[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1';& Import-Module '\\manage1cvg\boxshare\Boxstarter.chocolatey\Boxstarter.chocolatey.psd1' -DisableNameChecking -ArgumentList $true; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\common\tools\ChocolateyInstall.ps1' -installArguments '' -packageParameters ''"']
common not installed. An error occurred during installation:
 The directory name is invalid
```

Try running that command manually and see if you get the same error. I'm wondering if there is an issue with your share. If you do get the same error try running just:
``
Import-Module '\\manage1cvg\boxshare\Boxstarter.chocolatey\Boxstarter.chocolatey.psd1' -DisableNameChecking -ArgumentList $true
```
and see if you still get the error

**Comment by sooth** [comment]
Thank you for your response. I had tried that and it all works perfectly.

**Comment by mwrock** [comment]
hmm. ok. Do you get this error regardless of package or only the "common" package?

**Comment by sooth** [comment]
Yes, any custom package that I used to have.

**Comment by sooth** [comment]
I am desperate to get some sort of Boxstarter running again (I had no idea how much I truly use it) so I am installing it on a new machine. The steps so far are:

**On Server**
Run the installer on a new machine (B 2.6.25 Choco 0.9.9.8)
Run Boxstarter Shell as admin
"Set-BoxstarterShare BoxShare"
Set-BoxstarterConfig -LocalRepo \\\\davidm-5810\BoxShare
Set permissions for "Authenticated Users" to "Read"
Run my script to regenerate all of my custom packages
_`Boxstarter> & '.\Generate Packagers.ps1'
Attempting to build package from 'common.nuspec'.
Successfully created package 'common.1.0.0.nupkg'
Boxstarter: Created a temporary package common from common.txt in \\davidm-5810\BoxShare
common
Attempting to build package from 'Windows10.nuspec'.
Successfully created package 'Windows10.1.0.0.nupkg'
Boxstarter: Created a temporary package Windows10 from Windows10.txt in \\davidm-5810\BoxShare
Windows10`_

**On Client**
\\\\davidm-5810\BoxShare\Boxstarter Windows10 -DisableReboots
_`Installing the following packages:
Windows10
By installing you accept licenses for the packages.
Windows10 v1.0.0 (forced)
Windows10 not installed. An error occurred during installation:
 The directory name is invalid
The install of windows10 was NOT successful.
Windows10 not installed. An error occurred during installation:
 The directory name is invalid`_
https://www.youtube.com/watch?v=Pr3sBks5o_8

**Comment by sooth** [comment]
Based on the error in the client I went to the powershell command line and ran the following:
```

C:\..\Documents(2)> import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'
C:\..\Documents(3)> Import-Module '\\davidm\BoxShare\Boxstarter.chocolatey\Boxstarter.chocolatey.psd1' -DisableNameCheck
ing -ArgumentList $true
C:\..\Documents(7)> C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1 -packageScript 'C:\ProgramData\chocolat
ey\lib-bad\Windows10\tools\ChocolateyInstall.ps1'
Boxstarter: Setting PowerShell execution context to Unrestricted
Boxstarter: Invoke-Reboot must be called from a Boxstarter package.
Boxstarter: Invoke-Reboot must be called from a Boxstarter package.
Boxstarter: Invoke-Reboot must be called from a Boxstarter package.
+ Boxstarter starting Checking for updates...
Restarting windows update service
+ Boxstarter finished Checking for updates... 00:00:53.7614259
9 Updates found
```

**Comment by mwrock** [comment]
I'm gonna create similar environment locally to try and reproduce/fix this this weekend.

**Comment by mwrock** [comment]
OK. I at least got to the bottom of this, but fixing is going to require an update to choco.

When chocolatey launches its powershell process to run the package script, it sets the working directory of the process to the directory of the running assembly. This results in that error if you are pointing to a remote choco assembly as you are.

Here are some options to work around this:
* Rather than calling a remote boxstarter installation, you could push from a central install using `Install-BoxstarterPackage -Computernsme some_computer -Credential ...` This will install packages to a remote machine.
* Install boxstarter locally but point the local repository to the remote repository.

**Comment by sooth** [comment]
Thank you, the second option is the path I'll be taking, I can easily add that to my existing provisioning scripts.

**Comment by HolisticDeveloper** [comment]
Any progress on resolving this? Is there a chocolatey issue that it can be linked to?

**Comment by sooth** [comment]
The second solution was extremely easy and has been working perfectly since changing to it, so this really isn't much of an issue anymore.

**Comment by pauby** [comment]
As this was a Chocolatey issue with a workaround which resolved it I'm going to go ahead and close this now. If we need to reopen this in the future we can do that.
