### ISSUE TITLE
Web page code blocks overlap menu when viewing on small screen

### ISSUE THREAD

**Issue by dragon788** [chocolatey/boxstarter#183]
If I snap the webpage to the left or right in Chrome on a 1080p monitor (1920x1080) the code blocks maintain full width even though the sidebars and text try to shrink and flow.

It should further be noted this breaks clicking on any of the links in the left sidebar see #120 .
http://boxstarter.org/WebLauncher

![boxstartersiteissue](https://cloud.githubusercontent.com/assets/487774/16061761/94e953c4-3254-11e6-9432-33031bb4e516.PNG)

**Comment by dragon788** [comment]
It appears that 992px is the magic width for it to work, less than that and it overlaps the sidebar and breaks the clickability. I should note that this does NOT actually break the links, as I use Vimium for mouse-less browsing and I'm still able to activate link-hint mode and select the links from the sidebar, they just aren't clickable.

This was tested using https://chrome.google.com/webstore/detail/viewport-dimensions/kchdfagjljmhgapoonapmfngpadcjkhk to resize the page (reload the page after installing the extension and possibly set the timeout to 5 seconds). 992px works, 991 or less and it overlaps.

**Comment by pauby** [comment]
Related to #120

**Comment by pauby** [comment]
PR #391 resolved.
