### ISSUE TITLE
Local Repo Wont Change anymore

### ISSUE THREAD

**Issue by NewyorkDev** [chocolatey/boxstarter#184]
I have v2.8.29 installed and when I run 

Set-BoxstarterConfig -LocalRepo "C:\Windows\Folder\packages\dev\"

It only changes until I close the powershell windows or boxstartershell.

When I run the command again the local repo is appdata\local\boxstarter\buildpackages.

**Comment by mwrock** [comment]
`Set-BoxstarterConfig` should not only edit the immediate value of `$Boxstarter.LocalRepo` it edits the configuration file `boxstarter.config` located at `$boxstarter.base\boxstarter.config` and sets its `<LocalRepo>` node to the set value. Susequent imports of the boxstarter module should lookup that value in that config file for the initial localrepo path.

I'm not sure why this is breaking for you, but can you check the contents of that file after setting the localrepo to see if it is written to with the new path?

**Comment by pauby** [comment]
No updates to this issue in some time so closing it. Can reopen in the future if needed.
