### ISSUE TITLE
Non actionable error messages

### ISSUE THREAD

**Issue by mwrock** [chocolatey/boxstarter#19]
Migrated from https://boxstarter.codeplex.com/workitem/45

This may likely be on chocolatey's end but reporting here until I can verify. 

installing this gist reproduces: 
https://gist.github.com/cnwilkin/8670024/raw/3af21bb7979679f19055b68744428509555fbc3e/boxstarter

**Comment by pauby** [comment]
The gist is no longer available and the [web archive](https://web.archive.org/web/20171227030749/boxstarter.codeplex.com/workitem/45) doesn't provide any more information.
