### ISSUE TITLE
Find-Module causes Boxstarter to constantly reboot after installing PowerShell modules

### ISSUE THREAD

**Issue by willprice** [chocolatey/boxstarter#193]
I've been trying to build a boxstarter package to set up my development environment but can't seem to get past it constantly rebooting and never getting past a certain part of my installation.

I've got a copy of my boxstarter.log and the package I'm trying to install with the setup script I'm using to invoke it (making use of the Boxstarter web application)

https://gist.github.com/willprice/7ed866359f2677d553ca66ba3b77019e

It seems that boxstarter detects a pending reboot after running the following commands:

``` powershell
Install-PackageProvider -Name NuGet -Force
Install-Module -Force -Name Carbon
Install-Module -Force -Name PSReadLine
Install-Module -Force -Name Posh-SSH
Install-Module -Force -Name Pester
```

It then reboots in a cycle.

I don't see why these lines should trigger a pending reboot as one isn't necessary. Could be that I killed the boxstarter script previously at point that has left some files that trigger a reboot preventing the script from getting further?

I'm not really sure where to dig to debug this further.

Thanks for your cool project, I'm looking forward to having a scripted windows install.

**Comment by mwrock** [comment]
Well it makes sense why the loop starts where it does in your script because thats where boxstarter would do its first pending reboot check - its triggered by `cinst`. The mystery is why it loops continually. I have seen this happen before where installing a particular driver was causing a file to be added to the `PendingFileRename` registry and it was never getting deleted so that was causing the machine to always be in a pending reboot state.

The best way to track that down is to run `Get-PendingReboot`which you can find [here](https://gallery.technet.microsoft.com/scriptcenter/Get-PendingReboot-Query-bdb79542). That should include in its output WHY it thinks the machine is in a pending reboot state which will help us figure out what the next step would be to remedy the situation.

**Comment by willprice** [comment]
Hi @mwrock,

Thanks for your response and your pointers. I've had a look into the issue leveraging `Get-PendingReboot` and have made some headway.


I'm trying to install some powershell modules using `Install-Module` suspecting this to be the cause I wrote a function to install the module if it wasn't already installed and up to date, but I kept getting reboots.

```ps1
function Install-PSModule ([string] $ModuleName)
{
  $existingVersion = $(Get-Module -ListAvailable -Name $ModuleName | Select-Object -First 1).Version
  $newestVersion = $(Find-Module -Name "$ModuleName" | Select-Object -First 1).Version
  if (-Not $existingVersion) {
    Install-Module -Name "$ModuleName"
    Write-BoxstarterMessage "Installing Powershell module $ModuleName (v$newestVersion)"

  } elseif ($newestVersion -gt $existingVersion) {
        Write-BoxstarterMessage "Upgrading Powershell module $ModuleName from v$existingVersion to v$newestVersion"
        Install-Module -Force -Name "$ModuleName"
  } else {
        Write-BoxstarterMessage "Powershell module $ModuleName is already at the latest version (v$existingVersion)"
  }
}
```

It seemed odd that this was still causing file renames so I had a look at the temp files being created...

```xml<?xml version="1.0" encoding="utf-8"?>
<SoftwareIdentity xmlns="http://standards.iso.org/iso/19770/-2/2015/schema.xsd" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  
    xmlns:discovery="http://packagemanagement.org/discovery"
    
    patch="false"
    media="(OS:windows)"
    name="OneGet.Providers"
    tagVersion="1" uniqueId="OneGet.Providers.1"
    version="1.15.194.0" versionScheme="multipartnumeric">

    <!--
        This swidtag is a Discovery Feed that has pointers to the SWIDTAGs for
        the providers that the bootstrapper can download.
    -->

     <Link
        href="https://oneget.org/nuget-2.8.5.205.package.swidtag"
        type="application/swid-tag+xml"
        rel="package"
        
        discovery:name="nuget"
        discovery:latest="true"
        discovery:version="2.8.5.205"
        media="(OS:windows)"
    />

    <Link
        href="https://oneget.org/ChocolateyPrototype-2.8.5.130.package.swidtag"
        type="application/swid-tag+xml"
        rel="package"
        
        discovery:name="chocolatey"
        discovery:latest="true"
        discovery:version="2.8.5.130"
        media="(OS:windows)"
    />

    <Link
        href="https://oneget.org/nugetv2.feed.swidtag"
        type="application/swid-tag+xml"
        rel="feed"
        
        discovery:name="nuget"
        media="(OS:windows)"
    />

    <Link
        href="https://oneget.org/chocolateyprototype.feed.swidtag"
        type="application/swid-tag+xml"
        rel="feed"
        
        discovery:name="chocolatey"
        media="(OS:windows)"
    />
</SoftwareIdentity>
```

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<SoftwareIdentity
    xmlns="http://standards.iso.org/iso/19770/-2/2015/schema.xsd"
    xmlns:discovery="http://packagemanagement.org/discovery"
    
    name="nuget"
    versionScheme="multipartnumeric"
    media="(windows)"
    tagVersion="1"    version='2.8.5.205' 
    uniqueId='nuget.2.8.5.205'
>

  <Meta
      providerName="nuget"
      providerVersion='2.8.5.205'
      summary="NuGet provider for the OneGet meta-package manager"
  />

  <Link
      href='https://oneget.org/Microsoft.PackageManagement.NuGetProvider-2.8.5.205.dll'
      type="application/octet-stream"
      rel="installationmedia"

      discovery:targetFilename="Microsoft.PackageManagement.NuGetProvider.dll"
      discovery:type="assembly"
      media="(OS:windows)"
  />
 </SoftwareIdentity>
```

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<SoftwareIdentity
  xmlns="http://standards.iso.org/iso/19770/-2/2015/schema.xsd"
  xmlns:discovery="http://packagemanagement.org/discovery"

  name="chocolatey"
  versionScheme="multipartnumeric"
  media="(windows) and (PackageManagement) and (min-PackageManagement.api:2) NOT (windows-nano)"
  tagVersion="1"    version='2.8.5.130'
  uniqueId='chocolateyprototype.2.8.5.130'>

  <Meta
    providerName="chocolateyprototype"
    providerVersion='2.8.5.130'
    summary="ChocolateyPrototype provider for the OneGet meta-package manager" />

  <Link
    href='https://oneget.org/ChocolateyPrototype-2.8.5.130.exe'
    type="application/octet-stream"
    rel="installationmedia"

    discovery:targetFilename="ChocolateyPrototype.exe"
    discovery:type="assembly"
    media="(OS:windows)" />
</SoftwareIdentity>
```


```ps1
# MinimalBox.ps1

echo (Get-PendingReboot)
Find-Module -name  "psreadline"
echo (Get-PendingReboot)
```

Causes the following in an Admin terminal:
```


PS C:\Windows\system32> C:\Users\Will\Desktop\MinimalBox.ps1
Computer           : DESKTOP-2Q4RGDG
CBServicing        : False
WindowsUpdate      : False
CCMClientSDK       : 
PendComputerRename : False
PendFileRename     : False
PendFileRenVal     : 
RebootPending      : False

Name                       : PSReadline
Version                    : 1.2
Type                       : Module
Description                : Great command line editing in the PowerShell console host
Author                     : Microsoft Corporation
CompanyName                : lzybkr
...
Computer           : DESKTOP-2Q4RGDG
CBServicing        : False
WindowsUpdate      : False
CCMClientSDK       : 
PendComputerRename : False
PendFileRename     : True
PendFileRenVal     : {\??\C:\Users\Will\AppData\Local\Temp\Microsoft.PackageManagement\21, }
RebootPending      : True
PS C:\Windows\system32> 
```

It appears `Find-Module` is updating some sort of package cache which will then be moved somewhere.

I presume this isn't a particularly niche use of boxstarter, I wonder how I can help fix it so that others don't run into the same errors--any suggestions on how I can help?

Many thanks!

**Comment by mwrock** [comment]
Wow that is odd. I would not expect a `Find-Module` to trigger a pending file rename, but it clearly is.

One thing you can try is disabling reboots. Running from the web launcher, you can do this by adding `/nr/` just after the `package/` in the url. If your script can run without the need for reboots (many/most can) then that gets atound reboots alltogether.

However if you do nee reboots, we could also look at possibly adding a setting to ignore the pending file rename class of pending reboots.

**Comment by willprice** [comment]
Hi Matt,

I think I could run my script so that it can run without reboots, I'm not doing anything particularly special (just installing updates, packages, setting windows explorer options).

I've had a bit more of a poke around and it seems OneGet has an open bug issue regarding Get-PackageProvider causing pending file renames: https://github.com/OneGet/oneget/issues/179
I wonder if the two are related.

I think it would be reasonable to wait for the new OneGet release to drop and see whether that remedies the issue, if not then maybe it would adding flags to ignore certain classes of pending reboots might be a good idea.

Thanks

**Comment by willprice** [comment]
Hi Matt,
I've had a think about this, and have a possible general solution--I'd be interested to know what you think of the approach...

One could implement a fence construct that bounds a set of instructions, in this fence we'd record pending reboots before and pending reboots after. Calculating the diff of pending reboots before and after would give us the entries created in the fence that we could ignore for the remainder of the boxstarter script.

If you think it's a sensible approach I could have a bash at working on this as I'd like to learn a bit more powershell!

**Comment by dragon788** [comment]
@willprice I seem to be running into something similar where the system thinks there is a pending reboot so Boxstarter just reboots in loop and never actually gets started installing the packages I've requested. It would be awesome if there was a way to work around this in Boxstarter by detecting if it was one of the "known bad" paths that is triggering the PendingRename status so that Boxstarter doesn't just loop forever.

**Comment by pauby** [comment]
@willprice did https://github.com/OneGet/oneget/issues/179 being fixed resolve this issue?

**Comment by willprice** [comment]
Hey @pauby, I'll try and test out tomorrow and see whether I can still replicate or not.

**Comment by pauby** [comment]
@willprice Any update on this?

**Comment by willprice** [comment]
Ran the gist I originally posted and it seems fine now :)
