### ISSUE TITLE
Cleanup chocolatey interception handle interception in packages.config and nuspec dependencies

### ISSUE THREAD

**Issue by mwrock** [chocolatey/boxstarter#20]
Migrated from https://boxstarter.codeplex.com/workitem/30

Cleanup chocolatey interception handle interception in packages.config and nuspec dependencies

**Comment by pauby** [comment]
The link in this is no longer available (as you'd expect) so needing more information on this one as it's not clear what the issue is.

**Comment by gep13** [comment]
@pauby Not sure that there was much additional information on the codeplex issue either...

https://web.archive.org/web/20171227030750/https://boxstarter.codeplex.com/workitem/30

**Comment by pauby** [comment]
Not enough information to proceed with this. If that changes happy to re-open.
