### ISSUE TITLE
WebLaunch Unknown Publisher

### ISSUE THREAD

**Issue by berney** [chocolatey/boxstarter#205]
When I try http://boxstart.org/package/sysinternals as per the example the WebLauncher gets a Application Run - Security Warning, Publisher cannot be verified. Publisher: Unknown Publisher. The shield is red because the publisher is unknown.

In the example http://boxstarter.org/WebLauncher the screenshot shows "Publisher: Open Source Developer, Boxstarter.org" with a yellow shield because it came from the Internet.

IIUC these packages are dynamically created based on the URL. If that's the case, I'm not sure this can be fixed easily without something like a networked HSM for code signing or pre-generating at least common cases and signing them.

I'm not sure if its possible (or easy) to have the binary pre-built and signed and just have arguments to it be dynamic.

This issue combined with the lack of SSL/TLS (#106) makes leaves no protection against MitM and on the fly trojaning of the executables.

**Comment by pauby** [comment]
The web launcher confirms the publisher is now known:

![image](https://user-images.githubusercontent.com/12760779/54565748-fbe5bb80-49c6-11e9-9790-767e3da63ae7.png)

**Comment by berney** [comment]
This issue is not resolved, your just saying that the dialog says the publish is unknown, which is what I said already. The vulnerability is still there. The download could be malicious. The receiver has no way to authenticate if the update is from the legitimate source and has not been tampered with.

**Comment by flcdrg** [comment]
Hi @berney,

@pauby showed that the publisher *is* known (see his screenshot).

Can you clarify why you don't think it is?

Should it say something besides "Chocolatey Software, Inc"?

David

**Comment by berney** [comment]
My bad I totally misread that. Thanks.
