### ISSUE TITLE
Feature: Implement disabling IE first run wizard

### ISSUE THREAD

**Issue by dragon788** [chocolatey/boxstarter#209]
Just spent a bit of time looking into this. Even on servers with IE ESC disabled the first run wizard hasn't been run so when trying to automate anything with `Invoke-WebRequest` you have to use `-UseBasicParsing` which really limits how well you can automate walking through a webpage's elements. The solution of course is to disable the first run wizard, which can be done via the Registry fairly easily, though it does appear to differ slightly depending on if you are on 2012r2/Win10 or an earlier version.

2012r2/Win10 (IE11)
```
[HKEY_LOCAL_MACHINE\Software\Microsoft\Internet Explorer\Main]
"DisableFirstRunCustomize"=dword:00000001
```

Earlier versions (IE9)
```
[HKEY_LOCAL_MACHINE\Software\Policies\Microsoft\Internet Explorer\Main]
“DisableFirstRunCustomize”=dword:00000001
```

Wrapping this up as another "WinConfig" style item would be awesome.

**Comment by corbob** [comment]
Given that IE is officially unsupported by Microsoft, I'd suggest perhaps a `Disable-BrowserFirstRunWizard` or something to that effect that sets both the IE registry keys, and the Edge registry keys. The Edge one is: `HKLM\Software\Policies\Microsoft\Edge\HideFirstRunExperience`

**Comment by pauby** [comment]
@mwallner can you fix the labels on this issue now that it's been closed?
