### ISSUE TITLE
Boxstarter/Choco Packer and Azure Arm

### ISSUE THREAD

**Issue by deckerjohn** [chocolatey/boxstarter#216]
Hello,

I was hoping someone here might know the answer and I've been trying to figure this out.  I'm fairly new to DevOps and Cloud

If I use packer with Azure ARM my template seems to go fine and I can run boxstarter/Chocolatey as inline scripts. (successfully) I'm just doing basic stuff such as notepad++ etc to try to learn this
 I've noticed that I cant seem to upgrade powershell with either boxstarter or choco and get an error 5.    Is that a situation where I need to use that "evalated user" option in packer?

I run a sysprep   When I deploy my template my programs that I installed I've noticed that chocolatey and Boxstarter are gone.   Do I need to alter my sysprep lines to leave them intact?  I see lots of examples for virtualbox but not to many for Azure ARM.  Am I crazy for wanting to do this this way?

Relevant Lines
----------------------------------

"provisioners": [{
   "type": "windows-shell", 
   "inline": [
"@powershell -NoProfile -ExecutionPolicy Bypass -Command \"iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))\" && SET \"PATH=%PATH%;%ALLUSERSPROFILE%\\chocolatey\\bin",
"@powershell -NoProfile -ExecutionPolicy Bypass -Command \"import-module servermanager;add-windowsfeature web-server -includeallsubfeature\"",
"Choco Install Something"
"Choco install Boxstarter"
"@powershell -NoProfile -ExecutionPolicy Bypass  -Command \"import-Module Boxstarter.Choco;Command Here

"%WINDIR%\\system32\\sysprep\\Sysprep.exe /generalize /oobe"

]

}]
}

**Comment by mwrock** [comment]
Yes you definitely want to use Packer's elevated powershell provisioner when updating powershell. Installing powershell is not a "winrm friendly" operation and using the elevated provisioner will leverage a scheduled task to mitigate that.

Boxstarter installs its modules in the user's localappdata directory. Thats not ideal and there is an issue to move it. When sysprep generalizes the image, it will blow away user profiles including the boxstarter modules in localappdata.

**Comment by Jamie-BitFlight** [comment]
@deckerjohn I have been doing this same thing. To get around this error, don't use elevated credentails, they aren't mentioned as an option in the packer documentation with azufrerm, and it works perfect when you stop using them.

However for your second error, my workaround was to:
install chocolatey and boxstarter
call packer's win-reboot
run the boxstarter commands via powershell (no elevated priv)
Reboot again
uninstall boxstarter
run sysprep

**Comment by pauby** [comment]
As this issue has been resolved I'm going to go ahead and close it. If we need to reopen again in the future we can do so.
