### ISSUE TITLE
Git Bash support?

### ISSUE THREAD

**Issue by another-guy** [chocolatey/boxstarter#217]
I'd love to use Boxstarter from Git Bash -- is it possible today? Say, `choco` can be invoked from git bash without any special steps...

**Comment by dragon788** [comment]
@another-guy most of Boxstarter is written in PowerShell, so probably not good odds of it working in Git Bash. If you install the pre-release PowerShell for Linux in Bash for Windows in Windows 10 you could possibly use Boxstarter there, but definitely at your own risk and YMMV.

**Comment by pauby** [comment]
As has been said, Boxstarter is written in PowerShell. choco.exe is a compiled executable. Closing this issue.
