### ISSUE TITLE
Unable to enable Remote Desktop seems to kill install

### ISSUE THREAD

**Issue by alanarthur** [chocolatey/boxstarter#218]
I've been testing a script on a Windows 10 VM and was happy with the result, so now running it on my physical PC, but I seem to be hitting a lot of issues. The physical PC is on a company domain (so has some GPOs applied), but I'm a local admin.

The first issue is that it repeatedly gets stuck 'Waiting for service 'SMS Agent Host (CCMEXEC) to stop...'. If I check Services, it shows as stopping. It'll either eventually stop, or I'll kill the process manually.

When it does get past that point, it then fails trying to Enable Remote Desktop. 

There was a problem enabling remote desktop. Make sure your operating system... etc

I dont have enable RemoteDesktop in my script, and it's actually already enabled by default.

Any ideas?

**Comment by pauby** [comment]
@alanarthur This was some time ago but I'm going to ask anyway in case it's still an issue ... is this still an issue and can you reproduce it and provide logs?

**Comment by TechWatching** [comment]
Still the issue for me.

**Comment by pauby** [comment]
@TechWatching Without the information requested above we can't help progress this.

**Comment by TechWatching** [comment]
I can reproduce it but where can I find the logs ?

**Comment by pauby** [comment]
We need enough information to reproduce it and logs confirming the errors and what happened. These would be the error itself, system logs etc.

**Comment by TechWatching** [comment]
Sorry for the delay to answer.

You can find  the boxstarter script I used [here](https://github.com/TechWatching/dotfiles/blob/features/initialization/boxstarter.ps1). I launched the script just by opening this url on my browser: `http://boxstarter.org/package/url?https://raw.githubusercontent.com/techWatching/dotfiles/blob/features/initialization/boxstarter.ps1`

This is an extract of the logs :
```OS:Microsoft Windows NT 10.0.19043.0
SCCM Client Version:5.00.9040.1044
SCCM Site:WKS
Service StartMode for SMS Agent Host:Auto
SMS Agent Host:Running: Auto
Exception:System.InvalidOperationException: Le service Background Intelligent Transfer Service est introuvable sur l'ordinateur '.'. ---> System.ComponentModel.Win32Exception: Le service spécifié n’existe pas en tant que service installé
   --- Fin de la trace de la pile d'exception interne ---
   à System.ServiceProcess.ServiceController.GenerateNames()
   à System.ServiceProcess.ServiceController.get_ServiceName()
   à System.ServiceProcess.ServiceController.GenerateStatus()
   à System.ServiceProcess.ServiceController.get_Status()
   à ConfigMgrHealth.MainWindow.ShowOtherClientInfo()
   à ConfigMgrHealth.MainWindow..ctor()
```
It's in french but basically said Backgound Intelligent Transfer Service could not be found on the computer.

**Comment by pauby** [comment]
Is the BITS Service installed and running / able to be started?

**Comment by pauby** [comment]
There has been no updates to this in some time, so I'm going to go ahead and close it. We can always reopen it again if needed.
