### ISSUE TITLE
Boxstarter reboots continuously on install large Windows update (1607 in this case)

### ISSUE THREAD

**Issue by aronovgj** [chocolatey/boxstarter#226]
I can reproduce this on several computers. Everything works well, all the updates install without issues, until that update comes. And then this happens all the time:

![img_20170214_140738 2](https://cloud.githubusercontent.com/assets/10271770/22930256/ac450f6e-f2bf-11e6-93ea-3afc70982b0c.jpg)

**Comment by mwrock** [comment]
Interesting. so it continually downloads and installs this one update? Your best bet is to dig into the event logs and win update log files for possible errors related to that update. Also check if you experience the same thing using the win update guii.

**Comment by aronovgj** [comment]
Using the win update gui everything works without issues. I don't think the update is ever installed. Not sure it is even ever redownloaded after the first time. 1607 is the anniversary update which is quite huge. But between reboots it only takes 30 seconds to a minute. I don't have a machine to get my hands on right now.

**Comment by pauby** [comment]
@aronovgj I know this was a while ago. I know you've installed it by now. But is this still an issue - have you seen it with other updates? Looking to gather information on this to triage it.

**Comment by FrederiqueRetsema** [comment]
This is still an issue with 2019-07 Cumulative Update for Windows 10 Version 1903 for x64-based Systems (KB4507453). I used the Windows 10 Enterprise edition version 1903 updated june 2019 as a starting point.

**Comment by pauby** [comment]
@FrederiqueRetsema Can you share your Boxstarter script you're using and the full command you using to start it off?

**Comment by FrederiqueRetsema** [comment]
https://github.com/FrederiqueRetsema/BoxstarterFRAIssue226

Set-ExecutionPolicy unrestricted
.\BoxstarterFRAIssue226

**Comment by FrederiqueRetsema** [comment]
@pauby: I tested this again, and this issue is solved.

Tested with 
- Windows 10 Business (Enterprise) version 18.09, 19.04, 19.09
- Windows 10 Consumer (Home) version 19.04, 19.09

Thank you all for fixing it!!

Frederique
