### ISSUE TITLE
Get-BitlockerVolume causing error 'does not have an associated BitLocker volume'

### ISSUE THREAD

**Issue by paulhanssen** [chocolatey/boxstarter#228]
Hi,

I'm getting the following error reported when I include the "boxstarter::default" Chef recipe in a Windows 10 Vagrant VM (PowerShell version 5.1.14393.0):

```
<S S="Error">Get-Win32EncryptableVolumeInternal :  does not have an associated BitLocker volume._x000D__x000A_</S>
<S S="Error">At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\BitLocker\BitLocker.psm1:707 char:42_x000D__x000A_</S>
<S S="Error">+ ...       $AllWin32EncryptableVolume = Get-Win32EncryptableVolumeInternal_x000D__x000A_</S>
<S S="Error">+                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~_x000D__x000A_</S>
<S S="Error">+ CategoryInfo          : NotSpecified: (:) [Write-Error], COMException_x000D__x000A_</S>
<S S="Error">+ FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Get-Win32EncryptableVolumeInternal_x000D__x000A_</S>
```

I'm posting here because the error is being caused by the following code in Boxstarter.Bootstrapper\Include-Reboot.ps1:

```
if(Get-Module Bitlocker -ListAvailable){
    Get-BitlockerVolume | ? {$_.ProtectionStatus -eq "On"  -and $_.VolumeType -eq "operatingSystem"} | Suspend-Bitlocker -RebootCount 1 | out-null
}
```

If there are no Bitlocker volumes detected, and error is thrown. The "fix" - at least to stop the error - is as follows:

```
    Get-BitlockerVolume -ErrorAction SilentlyContinue | ? {...
```

Thanks for making this product.

Cheers

**Comment by eeevans** [comment]
I too am getting this
Boxstarter: Disabling Automatic Updates from Windows Update
Attempting to build package from 'tmp7EB6.tmp.nuspec'.
Successfully created package 'C:\Users\vagrant\AppData\Roaming\BoxStarter\BuildPackages\tmp7EB6.tmp.1.0.0.nupkg'
Boxstarter: Created a temporary package tmp7EB6.tmp from C:\Users\vagrant\AppData\Local\Temp\\BoxstarterGist.txt in C:\Users\vagrant\AppData\Roaming\BoxStarter\BuildPackages
+ Boxstarter starting Calling Chocolatey to install tmp7EB6.tmp. This may take several minutes to complete...
Installing the following packages:
tmp7EB6.tmp
By installing you accept licenses for the packages.
[NuGet] Installing 'tmp7EB6.tmp 1.0.0'.
[NuGet] Successfully installed 'tmp7EB6.tmp 1.0.0'.

tmp7EB6.tmp v1.0.0 (forced)
tmp7eb6.tmp package files install completed. Performing other installation steps.
Boxstarter: Enabling Remote Desktop...
Boxstarter: Enabling Remote Desktop...
Boxstarter: Enabling Remote Desktop NLA ...
Boxstarter: Enabling Remote Desktop NLA ...
Boxstarter: Setting Windows Explorer options...
Boxstarter: Setting Windows Explorer options...
Boxstarter: Restarting the Windows Explorer process...
Boxstarter: Restarting the Windows Explorer process...
Boxstarter: Restarting the Windows Explorer process...
Boxstarter: Restarting the Windows Explorer process...
Boxstarter: Restarting the Windows Explorer process...
Boxstarter: Restarting the Windows Explorer process...
WARNING: The changes will take effect after you restart the computer PcsServerVM1.
Boxstarter: writing restart file
Boxstarter: writing restart file
Only an exit code of non-zero will fail the package by default. Set
 `--failonstderr` if you want error messages to also fail a script. See
 `choco -h` for details.
 The install of tmp7eb6.tmp was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey installed 1/1 packages. 0 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Boxstarter: found C:\Users\vagrant\AppData\Local\Boxstarter\Boxstarter.2988.restart we are restarting
+ Boxstarter finished Calling Chocolatey to install tmp7EB6.tmp. This may take several minutes to complete... 00:00:10.3436188
Boxstarter: writing restart file
Boxstarter: Restore Automatic Updates from Windows Update
Boxstarter: Restart Required. Restarting now...


Errors       : { does not have an associated BitLocker volume.}
ComputerName : localhost
Completed    : True
FinishTime   : 4/18/2017 4:44:34 PM
StartTime    : 4/18/2017 4:44:19 PM



Stderr from the command:

 does not have an associated BitLocker volume.
Get-Win32EncryptableVolumeInternal :  does not have an associated BitLocker volume.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\BitLocker\BitLocker.psm1:695 char:42
+ ...       $AllWin32EncryptableVolume = Get-Win32EncryptableVolumeInternal
+                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Get-Win32EncryptableVolumeInternal

**Comment by eeevans** [comment]
Still having this issue with version 2.9.14

**Comment by mwrock** [comment]
ok. trying this again with https://github.com/mwrock/boxstarter/commit/5f886ccdb3e7b02a1bf2b46fad940192c5fa7a9c

**Comment by pauby** [comment]
@paulhanssen @eeevans I appreciate this was some time ago but has this issue been resolved?

**Comment by paulhanssen** [comment]
I'm not directly involved using this software anymore, but your code change looks like the right one. So I'll close.
