### ISSUE TITLE
shell.application is not supported in Server 2016 Core/Nano

### ISSUE THREAD

**Issue by wspait** [chocolatey/boxstarter#229]
Firstly, thank you to all who have taken the time and effort to develop Boxstarter and Chocolatey!

We are having some issues with Server 2016 Core and Nano:

In the function `Setup-BoxstarterModuleAndLocalRepo` in InstallBoxStarterPackage.ps1 the usage of shell.application fails in Server 2016 Core and Nano.

shell.application throws a COM exception when executing

`$zipPackage = $shellApplication.NameSpace("$env:temp\Boxstarter\Boxstarter.zip") `

Using the .NET method in `System.IO.Compression.FileSystem` works, but

`Add-Type -AssemblyName System.IO.Compression.FileSystem` throws an exception in Nano.

It must be

`Add-Type -AssemblyName System.IO.Compression`, but omitting `.FileSystem` breaks support in other OSes.

**Comment by pauby** [comment]
PR #292 was merged. Closing this issue.
