### ISSUE TITLE
Boxstarter saves old machine name with AutoLogin credentials when renaming computer

### ISSUE THREAD

**Issue by wilddev65** [chocolatey/boxstarter#233]
I had setup a script to rename and add the machine into the domain and the current function used by Boxstarter to save the username and password when using Invoke-Reboot always saves the info with the old machine name. There does not seem to be a way of turning this off so the machine will use previously set AutoReboot info in the registry. As an FYI, the machine will do autologin correctly outside of Boxstarter as it does not append the machine name in the domain\username format in the registry setting of winlogon. Using the following has no effect;
$Boxstarter.RebootOK=$true
$Boxstarter.NoPassword=$True
$Boxstarter.AutoLogin=$False

**Comment by mwrock** [comment]
Unfortunately there is currently no way to override this in a sane manner. The best way I could think of to get around this would to be to override the Get-CurrentUser function and have it set the needed creds.

**Comment by wilddev65** [comment]
Not even just to turn off the saving of the creds so a previously configured autologin set in the registry would work?

**Comment by mwrock** [comment]
Oh if you want to have boxstarter NOT set logon creds, just dont enter a password. This may vary depending on how you are invoking boxstarter. If you are calling `Install-BoxstarterPackage`, then just dont supply the `-Credentials` arg. If you are running via the web installer, do not enter a password - just hit enter (3x) when prompted for a password.

**Comment by wilddev65** [comment]
I've tried both setting a different cred and no cred. In both cases Boxstarter saved the creds on reboot and tried to enter it anyway. There seemed to be no combination that resulted in it not saving the creds, even using $Boxstarter.Nopassword=$true had no effect. This was the reason I added this bug as I've spent quite a bit of time combing through the code you've written and the only thing I could see that was doing it was the Get-CurrentUser function. For now I worked around this by doing a two stage config where I run an unattend.xml to set the name I want in the first stage, so when I clone and do the SQL install where I need the box joined to the domain, Boxstarter has the correct login info. FYI here is my main script Boxstarter runs and the Boxstarter package script. (I'll add them to the bug) This is run by the same boxstarter.ps1 script in your collection.

**Comment by wilddev65** [comment]
[provision-stage2.txt](https://github.com/mwrock/boxstarter/files/853840/provision-stage2.txt)
[install-SQL.txt](https://github.com/mwrock/boxstarter/files/853842/install-SQL.txt)

**Comment by pauby** [comment]
@wilddev65 I know this was some time ago. Is this still an issue?

**Comment by pauby** [comment]
There has been no updates to this in some time, so I'm going to go ahead and close it. We can always reopen it again if needed.
