### ISSUE TITLE
The term 'refreshenv' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by patelcp** [chocolatey/boxstarter#235]
Having following error when running boxstarter:

 Boxstarter: Restarting the Windows Explorer process...
 refreshenv : The term 'refreshenv' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
 At C:\ProgramData\chocolatey\lib\temp_BoxstarterPackage\tools\ChocolateyInstall.ps1:426 char:5
 +     refreshenv
 +     ~~~~~~~~~~
     + CategoryInfo          : ObjectNotFound: (refreshenv:String) [], CommandNotFoundException
     + FullyQualifiedErrorId : CommandNotFoundException
[2017-03-21T22:15:07.8262866-07:00:::PID 3064] Boxstarter: Starting installs

Here is part of the script which is causing the error:

    choco install nodejs.install			--limitoutput

    refreshenv

    npm install -g gulp-cli
    npm install -g bower
    npm install -g yo
    npm install -g generator-helix

**Comment by mwrock** [comment]
boxstarter 2.9.0 just released. It embeds a much more recent version of chocolatey. You may want to try with 2.9.0.

**Comment by pauby** [comment]
@patelcp I know this was some time ago, but is this still an issue?

**Comment by pauby** [comment]
There has been no updates to this in some time, so I'm going to go ahead and close it. We can always reopen it again if needed.
