### ISSUE TITLE
Installing package with --x86 seems to be 'sticky' for subsequent packages

### ISSUE THREAD

**Issue by flcdrg** [chocolatey/boxstarter#240]
In my BoxStarter script, I install Notepad++ with the --x86 flag.

All packages that are installed after this seem to also install as 32bit packages. This is not new with 2.9.x - I saw the same problem with the previous version of BoxStarter.

Here is a gist which reproduces this problem on a new Azure VM - https://gist.github.com/flcdrg/87802af4c92527eb8a30/raw/7f28c4c77e3bf85346a813269cd8529ade8d1f65/boxstarter-bare.txt

As a workaround I'm going to try putting Notepad++ at the end of the script.

**Comment by pauby** [comment]
@flcdrg Is this still an issue? PR #306 was merged to fix the issue.

**Comment by flcdrg** [comment]
Good question.. When I get a chance, I'll try and repro it with the latest bits

**Comment by flcdrg** [comment]
Just confirmed that this is still a problem. Ran latest Boxstarter with a Gist like this:

```
cinst notepadplusplus --x86
cinst microsoft-teams
```

And it installs microsoft-teams as 32-bit

**Comment by flcdrg** [comment]
Here's the [boxstarter.log](https://github.com/chocolatey/boxstarter/files/2993274/boxstarter.log)

**Comment by flcdrg** [comment]
Line 2553 "User specified -x86 so forcing 32 bit"

**Comment by ferventcoder** [comment]
So this appears to be a Chocolatey issue - we'll fix it for 0.10.14.

**Comment by pauby** [comment]
@flcdrg Is this still an issue as it was fixed in 0.10.14 of Chocolatey?

**Comment by flcdrg** [comment]
I'm not sure. The Notepad++ x86 plugin compat issue has largely gone away, plus I pretty much use VS Code now anyway.

I'm closing this. If someone else hits it, feel free to reopen.
