### ISSUE TITLE
Screen output stops when running Boxstarter in Packer

### ISSUE THREAD

**Issue by KZeronimo** [chocolatey/boxstarter#242]
I'm just starting to investigate the use of Packer / Boxstarter to automate VM builds

I'm referencing Matt's blog [here](http://www.hurryupandwait.io/blog/creating-windows-base-images-for-virtualbox-and-hyper-v-using-packer-boxstarter-and-vagrant) which has been very helpful

I'm following the guidance to get windows updates installed prior to enabling WinRM - works reliably

I'm using the powershell provisioner to download and install Boxstarter and then 
`Install-BoxstarterPackage -PackageName a:\package.ps1 -Credential $cred`

package.ps1 contains
```
Enable-RemoteDesktop
Set-NetFirewallRule -Name RemoteDesktop-UserMode-In-TCP -Enabled True

cinst googlechrome
cinst git -params '"/GitAndUnixToolsOnPath"'
cinst git-credential-manager-for-windows
cinst conemu
cinst sourcecodepro
cinst visualstudiocode

Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
Install-Module posh-git -Scope CurrentUser
Install-Module oh-my-posh -Scope CurrentUser

Write-BoxstarterMessage "Defragging C:..."
Optimize-Volume -DriveLetter C

Write-BoxstarterMessage "Zeroing out empty space..."
wget http://download.sysinternals.com/files/SDelete.zip -OutFile sdelete.zip
[System.Reflection.Assembly]::LoadWithPartialName("System.IO.Compression.FileSystem")
[System.IO.Compression.ZipFile]::ExtractToDirectory("sdelete.zip", ".")
./sdelete.exe /accepteula -z c:
```

What's interesting is that after the completion of the first cinst I stop getting output from the provisioner and Packer transitions to 

> Gracefully halting virtual machine...

The Boxstarter package is continuing inside the VM and will run to completion - depending on how the shutdown timeout is set the Packer build may fail

It seems like the provisioner is being signaled prematurely that things are done - interestingly the Boxstarter package with the cinst stripped out works as expected

What am I missing?

**Comment by mwrock** [comment]
I would try adding:
```
      "elevated_user": "vagrant",
      "elevated_password": "vagrant"
```
to your powershell provisioner block in the packer template. Your username and password may vary. Using elevated creds will run the powershell in a scheduled task and gets around several shortcomings of vanilla winrm which may be the root of your issue.

**Comment by KZeronimo** [comment]
Thanks Matt - I failed to mention the provisioner setup - the results I'm seeing are with the use of elevated creds

Moving the execution of the scripts to autounattend - firstlogon works fine

I like you was looking for a way to move the bulk of the work to the provisioner where output would be bubbled up to packer console

I'll keep hacking on it

**Comment by brettjacobson** [comment]
@KZeronimo have you had any luck moving things to the provisioner step, instead of autounattend?

**Comment by rismoney** [comment]
Out of curiosity did you guys have http_proxy environment variable set on the nose where packer.exe runs?

**Comment by kirannhegde** [comment]
Were you able to get this working in the provisioning step?  Have you tried SSH as opposed to Winrm?

**Comment by pauby** [comment]
@KZeronimo I know this was some time ago but do you have any other info to share on this?

**Comment by pauby** [comment]
There has been no updates to this in some time, so I'm going to go ahead and close it. We can always reopen it again if needed.
