### ISSUE TITLE
Duplicate output running Boxstarter

### ISSUE THREAD

**Issue by flaviocdc** [chocolatey/boxstarter#244]
Running Boxstarter Version 2.9.5.

![image](https://cloud.githubusercontent.com/assets/688926/24633596/3b1e0950-187e-11e7-9c91-6af88a61573f.png)

I'm going to try come up with a simple .ps1 that causes this problem and update this issue.

**Comment by flatlinebb** [comment]
I'm having the same issue:

+ Boxstarter finished Calling Chocolatey to install NetFx3. This may take several minutes to complete... 00:00:00.3590758
+ Boxstarter finished Calling Chocolatey to install NetFx3. This may take several minutes to complete... 00:00:00.3590758
Boxstarter: Starting WindowsGadgetPlatform Uninstall ...
Boxstarter: Starting WindowsGadgetPlatform Uninstall ...
Boxstarter: Starting TabletPCOC Uninstall ...
Boxstarter: Starting TabletPCOC Uninstall ...
Boxstarter: Starting MediaCenter Uninstall ...
Boxstarter: Starting MediaCenter Uninstall ...
Boxstarter: Starting Printing-XPSServices-Features Uninstall ...
Boxstarter: Starting Printing-XPSServices-Features Uninstall ...
Boxstarter: Starting XPSServices Uninstall ...
Boxstarter: Starting XPSServices Uninstall ...
Boxstarter: Starting Xps-Viewer Uninstall ...
Boxstarter: Starting Xps-Viewer Uninstall ...
Boxstarter: Starting Enable Microsoft Update ...
Boxstarter: Starting Enable Microsoft Update ...
Boxstarter: Microsoft Update is already enabled, no action will be taken.
Boxstarter: Microsoft Update is already enabled, no action will be taken.
Boxstarter: Starting Windows Udpates Install ...
Boxstarter: Starting Windows Udpates Install ...
+ Boxstarter starting Checking for updates...
+ Boxstarter starting Checking for updates...
Restarting windows update service
Restarting windows update service

**Comment by flaviocdc** [comment]
Something as simple as https://boxstarter.org/package/nr/sysinternals repro's the problem.

![image](https://cloud.githubusercontent.com/assets/688926/25158790/edb3d62a-245f-11e7-8b1c-e733e92d36b1.png)

**Comment by brettjacobson** [comment]
Still happens in the latest version.  At least its only annoying, and not actually breaking anything!

**Comment by EntranceJew** [comment]
As I mentioned in #286 it is actually running each command twice, potentially wasting bandwidth and disk operations. For less-elegant install scripts, this can cause values/folders expected to be empty to be set, potentially destabilizing an otherwise stable install script like cygwin's.

**Comment by mattdkerr** [comment]
is there any work-around?

**Comment by dajo** [comment]
Just a quick ditto

**Comment by aaronk1** [comment]
+1

**Comment by cwigley** [comment]
+1 
This is actually causing a package install to hang for me. Anyone know what is the latest stable version? I have regressed a couple and I am still seeing the issue.

**Comment by TomasDeceuninck** [comment]
+1

**Comment by pauby** [comment]
Duplicate issue. See #286. Closing.
