### ISSUE TITLE
Error running Boxstarter script with existing licensed Chocolatey

### ISSUE THREAD

**Issue by flcdrg** [chocolatey/boxstarter#247]
Installed latest Chocolatey 0.10.5, added my license for Professional and installed `chocolatey.extension` package.

Then ran boxstarter via `START http://boxstarter.org/package/url` and seeing these errors being displayed:

```
Error when registering components for 'chocolatey.licensed.infrastructure.app.registration.ContainerBinding':
 Exception has been thrown by the target of an invocation.
Error when setting configuration for 'chocolatey.licensed.infrastructure.app.builders.ConfigurationBuilder':
 Exception has been thrown by the target of an invocation.
Error when setting environment for 'chocolatey.licensed.infrastructure.app.configuration.EnvironmentSettings':
 Exception has been thrown by the target of an invocation.
```

**Comment by cSharpRookie** [comment]
Did you find a solution to this problem?

**Comment by flcdrg** [comment]
No. Hoping there's a new Boxstarter version in the works that takes the latest Chocolatey bits

**Comment by mwallner** [comment]
CC @ferventcoder

**Comment by ferventcoder** [comment]
Fixed in 0.10.6 I believe with all of the API work that went in - 0.10.7 will have best fixes.

**Comment by mwrock** [comment]
just deployed new boxstarter with 0.10.7 choco!

**Comment by cSharpRookie** [comment]
It appears to be a timing issue, I just kept trying the command and eventually the timing was ok and it made the package.  

I was using version 10.7 of chocolatey and the latest version of boxstarter.

**Comment by ferventcoder** [comment]
@csharprookie boxstarter has a built-in choco, it doesn't use the system installed version of choco by default. So a new version of boxstarter needed to deploy to support this.

**Comment by ferventcoder** [comment]
Unless there is something there causing issues as well (like seen in the GUI)

**Comment by pauby** [comment]
Related to #241.

**Comment by Jvekka** [comment]
Is there a way to suppress the errors (or output)?

**Comment by lukebal** [comment]
@pauby What is the recommended way of moving forward with this? Error suppression? Not installing Chocolatey before using Boxstarter and having Boxstarter install chocolatey?
My goal is bootstrapping a fresh Windows 10 machine + installing licensed Chocolatey v10.13 + using Boxstarter to control the whole process

**Comment by pauby** [comment]
@lukebal I would have Boxtstarter install Chocolatey as needed. Boxstarter uses it's own 'Chocolatey' for package management.
