### ISSUE TITLE
Reply for ClickOnce support in Firefox.

### ISSUE THREAD

**Issue by Redsandro** [chocolatey/boxstarter#251]
It took some time, but the wish for re-introducing ClickOnce in FireFox was heard over at https://github.com/Microsoft/dotnet/issues/185#issuecomment-296322293

I think @staceyhaffner is gauging interest:
> Please add a reaction to communicate if you want my team to provide better ClickOnce support in FireFox.

**Comment by pauby** [comment]
Have a look at https://github.com/Microsoft/dotnet/issues/185#issuecomment-350208874 - this is not a Boxstarter issue but a Firefox Quantum one. There is no ClickOnce support for Firefox officially.
