### ISSUE TITLE
Using Boxstarter as a Packer Provisioner for Azure

### ISSUE THREAD

**Issue by Jamie-BitFlight** [chocolatey/boxstarter#254]
Hi,
1. For AzureRM in Packer, if you supply powershell elevated credentials you get an error when the powershell executes.
2. If you install boxstarter as one of the setup steps, it installs to the user apps direcrtory that does the install (user: packer), then when you run sysprep, the packer admin account that did the install is stripped out, which deletes the boxstarter bin files.

because of that, I was installing boxstarter, with chocolatey, making a new powershell session, and running the boxstarter install, then uninstalling boxstarter.
But that too caused errors with the install/uninstall procedure.

I have scrapped boxstarter for now, since it is consuming more time then I have to work around those issues. But I would love to use it, since the feature set you have made is ideal.

I think you already have it as a feature request, but is there a way to install to a location outside of the user home directory, so that the BIN files can persist through administrative user removal?
And be accessed by all users?

**Comment by mwrock** [comment]
You could try copying the `$env:appdata\boxstarter` directory to `$env:programdata` and adding that dir to your `$env:PSModulePath`.

**Comment by pauby** [comment]
@Jamie-BitFlight I appreciate this was some time ago but did you manage to get any further forward with this?

**Comment by Jamie-BitFlight** [comment]
No, Although I did follow your instructions and spent many more hours on testing options.
:(

**Comment by Jamie-BitFlight** [comment]
I am not sure if there are new options in Choco or BoxStarter which may resolve the issue of optionally choosing non-userspace installs.

**Comment by pauby** [comment]
Boxstarter still uses the user directory as far as I understand.

**Comment by pauby** [comment]
There has been no updated to this in some time so I'm going to go ahead and close it. We can always reopen it again if needed.
