### ISSUE TITLE
Defender module not imported automatically when running Boxstarter

### ISSUE THREAD

**Issue by levande** [chocolatey/boxstarter#259]
When trying to exclude folder from Windows defender through Boxstarter it ends up with this:
(Command that I try to run: set-mppreference -exclusionpath C:\BuildAgent)
```
Set-MpPreference : The 'Set-MpPreference' command was found in the module 'Defender', but the module could not be
loaded. For more information, run 'Import-Module Defender'.
At line:1 char:1
+ Set-MpPreference
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Set-MpPreference:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
```
If I test the command locally before running through boxstart it works. But after I have run it with boxstarter the command stops to work even if I try locally.

**Comment by mwrock** [comment]
Interesting. It seems something with the boxstarter/chocolatey environment is causing the defender module import to fail. Try adding `Import-Module Defender` to your package and see if that raises any error that may give a clue as to why.

**Comment by pauby** [comment]
@levande I appreciate this was some time ago but did you get any further with this?

**Comment by pauby** [comment]
There has been no updated to this in some time so I'm going to go ahead and close it. We can always reopen it again if needed.
