### ISSUE TITLE
choco pin and choco source do not work as expected when running in Boxstarter

### ISSUE THREAD

**Issue by flcdrg** [chocolatey/boxstarter#265]
Boxstarter 2.9.26 is misinterpreting `choco pin` and thinks there are package names to install, rather than pinning a package.

Such that `choco pin add -n=GoogleChrome` looks for a package named 'add' and also 'googlechrome'

> Install-BoxstarterPackage https://gist.githubusercontent.com/flcdrg/87802af4c92527eb8a30/raw/pin-example.ps1
> Boxstarter: Installing package https://gist.githubusercontent.com/flcdrg/87802af4c92527eb8a30/raw/pin-example.ps1
> Boxstarter Version 2.9.26
> (c) 2017 Matt Wrock. http://boxstarter.org
> 
> Boxstarter: Disabling Automatic Updates from Windows Update
> Attempting to build package from 'tmp3C90.tmp.nuspec'.
> Successfully created package 'C:\Users\David\AppData\Roaming\Boxstarter\BuildPackages\tmp3C90.tmp.1.0.0.nupkg'
> Boxstarter: Created a temporary package tmp3C90.tmp from https://gist.githubusercontent.com/flcdrg/87802af4c92527eb8a30/
> raw/pin-example.ps1 in C:\Users\David\AppData\Roaming\Boxstarter\BuildPackages
> ++ Boxstarter starting Calling Chocolatey to install tmp3C90.tmp. This may take several minutes to complete...
> Installing the following packages:
> tmp3C90.tmp
> By installing you accept licenses for the packages.
> [NuGet] Installing 'tmp3C90.tmp 1.0.0'.
> [NuGet] Successfully installed 'tmp3C90.tmp 1.0.0'.
> 
> tmp3C90.tmp v1.0.0 (forced)
> tmp3c90.tmp package files install completed. Performing other installation steps.
> + Boxstarter starting Calling Chocolatey to install add. This may take several minutes to complete...
> + Boxstarter starting Calling Chocolatey to install add. This may take several minutes to complete...
> Installing the following packages:
> add;GoogleChrome
> By installing you accept licenses for the packages.
> add not installed. The package was not found with the source(s) listed.
>  If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
>  Version: ""
>  Source(s): "https://licensedpackages.chocolatey.org/api/v2/;https://chocolatey.org/api/v2/"
> GoogleChrome v59.0.3071.104 already installed. Forcing reinstall of version '59.0.3071.104'.
>  Please use upgrade if you meant to upgrade to a new version.
> [NuGet] Uninstalling 'GoogleChrome 59.0.3071.104'.

**Comment by mwrock** [comment]
Boxstarter is currently very install/update centric. In other words, it does not work well with other choco commands. I experimented with a fix so that if one runs another command like `pin`, that command gets propperly forwarded to the chocolatey library call.

Unfortunate I think this is suffering from the same issue as #264 because although it is clearly passing pin to the choco dll, chocolatey is trying to perform an `install`. My hypothesis is that it does this because the "outer" package is performing an install and this "sticks" to the inner calls.

**Comment by mwallner** [comment]
*bump* - same here with `choco source`
I'm trying to install a `chocolatey-patches` package that uses `choco source` a couple of times i.e.
```
  $(choco source) | ForEach-Object { 
    $feed = $_
    foreach ($lf in $legacyFeeds) {
      if (-Not $feed.Contains($lf)) {
        continue
      }
      $feedname = $feed.Split(" ")[0]
      Remove-ChocoFeed $feedname
    }
  }
```

Any chance to get this fixed soon?

**Comment by mattdkerr** [comment]
Use Install-ChocolateyPinnedTaskBarItem instead

**Comment by flcdrg** [comment]
Are you sure? I think you're mixing two different concepts.

Choco pin fixes the version number so that chocolatey won't upgrade the package.

The cmdlet you mention is for creating a shortcut on the Windows task bar (which no longer works on Windows 10 anyway)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mwallner** [comment]
Boxstarter function "chocolatey" completely ignores what command is passed to chocolatey, (i.e. install, update, source, pin, ...)
see https://github.com/chocolatey/boxstarter/blob/master/Boxstarter.Chocolatey/Chocolatey.ps1#L94

There should be something like
```
    if ($command -ne "install" -and $command -ne "update") {
        Call-Chocolatey @PSBoundParameters @args
        return
    }
```
- that would probably fix this issue and a couple of other "weird issues"

need to look a bit further into this, but want to get it fixed for the next release.
