### ISSUE TITLE
{Help} Credential

### ISSUE THREAD

**Issue by Skolzack** [chocolatey/boxstarter#280]
When using these parameters `$Boxstarter.RebootOk=$true
$Boxstarter.NoPassword=$false
$Boxstarter.AutoLogin=$true` why he only asks for credentials after the first reboot and not when the script starts for the first time?

**Comment by mwrock** [comment]
Its best not to change those parameters at all and instead simply pass credentials to the `-Credentials` arg of `Install-BoxstarterPackage`

**Comment by Skolzack** [comment]
So I need to remove these parameters from my script and use -Credentials arg?

My script: https://raw.githubusercontent.com/nibodev/machineSetup/master/Boxstarter.MachineSetup.ps1

**Comment by mwrock** [comment]
thats correct. (Correction: `-credential`)

**Comment by flatlinebb** [comment]
-Credential was giving me an error with the latest version of boxstarter console. Also, there are blank lines, that start with "VERBOSE:" and nothing else.
I will try to get logs and screenshots when the machine is back up.

**Comment by mwrock** [comment]
Yes. `-Credential` takes a PSCredential. You could create one with `Get-Credential`:

```
Install-BoxstarterPackage -Package http://xxx.xxxxxxxxxxx.xxx/xxxxxxxx_deploy.txt -
Credential (Get-Credential TSG)
```

**Comment by flatlinebb** [comment]
Thanks for the tip, it did prompt me for the credentials. I will update my
documentation to reflect this format.

**Comment by gep13** [comment]
@Skolzack @flatlinebb I am going to go ahead and close this issue.  Let us know if you have any follow up questions/concerns.
