### ISSUE TITLE
Boxstarter always installs x86 version of Git

### ISSUE THREAD

**Issue by SaintGimp** [chocolatey/boxstarter#283]
I can't get Boxstarter to install the 64-bit version of Git.  It always installs the x86 version of Git even though I'm on a 64-bit machine.  Installing outside of Boxstarter (via `choco install git`) does correctly install the x64 build.

Steps to repro:
I created a Boxstarter script file with one line:
`choco install git`

I invoked it this way:
`Install-BoxstarterPackage -PackageName $Env:UserProfile\Boxstarter-Git.ps1 -DisableReboots`

I got this output:
```
+ Boxstarter starting Calling Chocolatey to install git. This may take several minutes to complete...
Installing the following packages:
git
By installing you accept licenses for the packages.
[NuGet] Attempting to resolve dependency 'git.install (= 2.14.1)'.
[NuGet] Attempting to resolve dependency 'chocolatey-core.extension (≥ 1.3.1)'.
[NuGet] Attempting to resolve dependency 'chocolatey (≥ 0.10.7)'.
Progress: Downloading git 2.14.1... 100%
Progress: Downloading git 2.14.1... 100%
[NuGet] Installing 'git.install 2.14.1'.
[NuGet] Successfully installed 'git.install 2.14.1'.

git.install v2.14.1 [Approved]
git.install package files install completed. Performing other installation steps.
Using Git LFS
Using Git LFS
Installing git.install...
Installing git.install...
git.install has been installed.
git.install has been installed.
git.install installed to 'C:\Program Files (x86)\Git'
git.install installed to 'C:\Program Files (x86)\Git'
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of git.install was successful.
  Software installed to 'C:\Program Files (x86)\Git\'
[NuGet] Installing 'git 2.14.1'.
[NuGet] Successfully installed 'git 2.14.1'.

git v2.14.1 [Approved]
git package files install completed. Performing other installation steps.
 The install of git was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey installed 2/2 packages. 0 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
+ Boxstarter finished Calling Chocolatey to install git. This may take several minutes to complete... 00:01:11.4364922
```
Note the `git.install installed to 'C:\Program Files (x86)\Git'` line.

When I install git directly via Chocolatey:
`choco install git`

I get this output:
```
Chocolatey v0.10.7
Installing the following packages:
git
By installing you accept licenses for the packages.
Progress: Downloading git 2.14.1... 100%

git.install v2.14.1 [Approved]
git.install package files install completed. Performing other installation steps.
The package git.install wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[N]o/[P]rint): y

Using Git LFS
Installing 64-bit git.install...
git.install has been installed.
git.install installed to 'C:\Program Files\Git'
  git.install can be automatically uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of git.install was successful.
  Software installed to 'C:\Program Files\Git\'

git v2.14.1 [Approved]
git package files install completed. Performing other installation steps.
 The install of git was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey installed 2/2 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```
Note the `Installing 64-bit git.install` line.

Because there's no Chocolatey parameter to force a 64-bit install (only to force a 32-bit install), I'm not sure how to work around this.

**Comment by SaintGimp** [comment]
This may or may not be related to #240.

**Comment by mscrivo** [comment]
Seeing the same issue here, except that git is the first thing we install after boxstarter itself.  You can see our bootstrap file here: https://github.com/NudgeSoftware/Public/blob/master/bootstrap-machine.ps1

**Comment by mattdkerr** [comment]
I see all packages installing the 32-bit option:
git
gittfs
visualstudiocode
micro
(etc)
reproduced on 2.10.3 boxstarter

**Comment by Chopperbp** [comment]
Try this:
function Install-ChocolateyInstallPackageOverride {
param(
  [string] $packageName, 
  [string] $fileType = 'exe',
  [string] $silentArgs = '',
  [string] $file,
  **[string] $file64, # missing!!**
  $validExitCodes = @(0)
)

**Comment by ferventcoder** [comment]
I am guessing this has to do with something in boxstarter running in 32-bit mode.

**Comment by sayresVT** [comment]
I believe https://github.com/mwrock/boxstarter/issues/283#issuecomment-352024589 identified the source of the problem.  I was seeing this issue with all packages that were attempting to utilize the `$file64` param that was added in a more recent version of Chocolatey but was absent from Install-ChocolateyInstallPackageOverride.  I'm a bit of a powershell novice, but I think https://github.com/mwrock/boxstarter/pull/306 should hopefully address the issue.

**Comment by pauby** [comment]
PR #306 merged. Closing this issue.
