### ISSUE TITLE
Chocolatey installs should not be forced

### ISSUE THREAD

**Issue by mattdkerr** [chocolatey/boxstarter#290]
I would like to avoid a forced uninstall/install in the boxstarter script because it can cause problems for customized installations of machines provisioned initially by someone else.

**Comment by mwallner** [comment]
This could be a new feature (i.e. `-SkipAlreadyInstalled`), though I would not change the default behavior as it would be a breaking change in basically every Boxstarter environment I know of.
In a perfect world, all packages should be idempotent and a forced reinstall should just re-apply the wanted state.
(I know this is tricky/not-possible if the packages modify HKCU / appdata etc.. just saying :joy:)

**Comment by pauby** [comment]
Why is Boxstarter forcing the installs?

**Comment by mwallner** [comment]
afaik it's been there since the dawn of Boxstarter. maybe @mwrock can shed some light onto the 'why'?
I kinda like it because it will "do the same things/installations" each time, no matter if something has been installed prior or not.

**Comment by pauby** [comment]
@mattdkerr I _just_ noticed this:

>  installations of machines provisioned initially by someone else.

Boxstarter is intended to be run on a 'bare machine', i.e. something that has not been configured prior to it running. If you are concerned about it overwriting a config made by something else, then Boxstarter may not be the right tool for you.

@mwallner pointed out the reason why it's there, so I think I'm going to go ahead and close this as something we're not going to change. We can always open it again if needed.
