### ISSUE TITLE
Add WS2016 support for built in PSRemoting

### ISSUE THREAD

**Issue by theterminator3000** [chocolatey/boxstarter#295]
Add PowerShell direct support to allow sysadmins to install packages in VM as an addition to other methods available.

[Documentation](https://blogs.technet.microsoft.com/virtualization/2015/05/14/powershell-direct-running-powershell-inside-a-virtual-machine-from-the-hyper-v-host/)

**Comment by pauby** [comment]
@theterminator3000 I know this was some time ago but can you give us a use case for this?

**Comment by theterminator3000** [comment]
Erm this has been a while and I can no longer remember. I'm going to close this issue
