### ISSUE TITLE
Calling Boxstarter from a scheduled task does not work

### ISSUE THREAD

**Issue by Castingnet** [chocolatey/boxstarter#297]
1. I made sure the script is running under elevated mode
2. I made sure there is enough delay after system startup
3. When I run the registered scheduled task manually(through task scheduler GUI), the issue will not occur

Here is the code to do the register of the task scheduler:
```
$TaskActionArgument ="-noprofile -command `"&{start-process powershell -argumentList '-File C:\users\administrator\updatescript\boxstarter.ps1 -verb runas'}`""
$TaskAction = New-ScheduledTaskAction -Execute "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -argument $TaskActionArgument
$TaskTrigger = New-ScheduledTaskTrigger -AtStartup
Register-ScheduledTask -TaskName boxstarter -Action $TaskAction -Trigger $TaskTrigger -User administrator -Password Vmc12svt -RunLevel Highest
```

Here is the last lines of log I get from boxstarter:

> [2018-01-11T05:27:11.0085025-08:00:::PID 2772] Boxstarter: restoring current directory location to C:\Windows\system32
> [2018-01-11T05:27:11.0866436-08:00:::PID 2772] Boxstarter: Created a temporary package tmp5494.tmp from c:\users\administrator\updatescript\package.ps1 in C:\programdata\boxstarter\BuildPackages
> [2018-01-11T05:27:11.0866436-08:00:::PID 2772] Boxstarter: Created a temporary package tmp5494.tmp from c:\users\administrator\updatescript\package.ps1 in C:\programdata\boxstarter\BuildPackages
> [2018-01-11T05:27:11.1178792-08:00:::PID 2772] Boxstarter: Deleting previous tmp5494.tmp package
> [2018-01-11T05:27:11.1647558-08:00:::PID 2772] Boxstarter: Installing 1 packages from C:\programdata\boxstarter\BuildPackages;http://chocolatey.org/api/v2;http://www.myget.org/F/boxstarter/api/v2
> [2018-01-11T05:27:11.4772539-08:00:::PID 2772] Boxstarter: Installing 1 packages
> [2018-01-11T05:27:11.4772539-08:00:::PID 2772] Boxstarter: Checking for Pending reboot
> [2018-01-11T05:27:12.9478739-08:00:::PID 2772] Boxstarter: Detected Pending reboot
> [2018-01-11T05:27:12.9478739-08:00:::PID 2772] @{Computer=WIN-6HSHKOKP31E; CBServicing=True; WindowsUpdate=False; CCMClientSDK=; PendComputerRename=False; PendFileRename=False; PendFileRenVal=; RebootPending=True}
> [2018-01-11T05:27:13.1022560-08:00:::PID 2772] Boxstarter: writing restart file
> [2018-01-11T05:27:13.1022560-08:00:::PID 2772] Boxstarter: writing restart file
> [2018-01-11T05:27:13.2428825-08:00:::PID 2772] Boxstarter: Restore Automatic Updates from Windows Update
> [2018-01-11T05:27:13.2987702-08:00:::PID 2772] Boxstarter: Enabling UAC
> [2018-01-11T05:27:13.3210075-08:00:::PID 2772] Boxstarter: UAC Enabled. Disabling...
> [2018-01-11T05:27:13.3366327-08:00:::PID 2772] Boxstarter: Disabling UAC
> [2018-01-11T05:27:13.3680116-08:00:::PID 2772] Boxstarter: Securely Storing WIN-6HSHKOKP31E\Administrator credentials for automatic logon
> [2018-01-11T05:27:13.9928920-08:00:::PID 2772] Boxstarter: Logon Set
> [2018-01-11T05:27:14.0241325-08:00:::PID 2772] + Boxstarter finished Installation session. 00:00:12.4392627
> [2018-01-11T05:27:14.0397597-08:00:::PID 2772] Boxstarter: Restart Required. Restarting now...
> [2018-01-11T05:27:14.3366345-08:00:::PID 2772] Boxstarter: Composing record for pipeline...
> [2018-01-11T05:27:14.3522593-08:00:::PID 2772] Boxstarter: writing object...
> [2018-01-11T05:27:14.3522593-08:00:::PID 2772] Boxstarter: object written...

Sorry I couldn't provide more information as I'm not familiar with windows platform.

**Comment by mwrock** [comment]
Boxstarter uses "Startup Programs" to invoke itself after startup. That might not work in the context of a scheduled task if it is non interactive with no active desktop.

**Comment by pauby** [comment]
@Castingnet I appreciate this was some time ago but did you manage to resolve this or do you have any more info?

**Comment by pauby** [comment]
There has been no updated to this in some time so I'm going to go ahead and close it. We can always reopen it again if needed.
