### ISSUE TITLE
Chocolatey Packages - investigate packages failing verifier

### ISSUE THREAD

**Issue by gep13** [chocolatey/boxstarter#313]
https://chocolatey.org/packages/Boxstarter.Azure/2.11.0
https://chocolatey.org/packages/Boxstarter.TestRunner/2.11.0

@mwrock do you remember having any issues with these in the past?

I will need to test these out locally to see what is going on.

**Comment by mwrock** [comment]
I think they did fail regularly.

**Comment by lavahot** [comment]
Looks like there's some [dependency problem](https://gist.github.com/choco-bot/82af634b61a4e6cc334a0e0a76b4d99c#file-install-txt-L4043) What version of PS does the verifier run?

**Comment by pauby** [comment]
It's what is in the box with [2012 R2](https://en.wikipedia.org/wiki/PowerShell#PowerShell_4.0)

**Comment by lavahot** [comment]
OH. Then if PS 5.0 is a hard dependency for Azure Powershell then I can see a few options:

-Short term: get moderator approval to bypass the failing tests
-Long term: get whoever maintains the verifier to update to PS 5.0
-Wonky: Add powershell 5.0+ package as a dependency to the azurepowershell package.

**Comment by pauby** [comment]
@lavahost (appreciate this is an old comment).

2 and 3 are not options unfortunately. 1 is the only option available.

**Comment by pauby** [comment]
Both [Azure.Boxstarter](https://chocolatey.org/packages/Boxstarter.Azure/2.11.0) and [Boxstarter.TestRunner](https://chocolatey.org/packages/Boxstarter.TestRunner/2.11.0) have been exempted from testing due to .NET 4.5.2 dependency.
