### ISSUE TITLE
Hyper-v package install issues - get this error - Message : Cannot bind parameter 'Path' to the target. Exception setting "Path": "C

### ISSUE THREAD

**Issue by rajganeshp** [chocolatey/boxstarter#326]
I'm trying to install sublimetext3 on my Hyper-v guest, but I keep getting some path errors.

PS C:\> "neptune10" | Enable-BoxstarterVM -Credential $cred |Install-BoxstarterPackage -PackageName sublimetext3
Boxstarter: Configuring local PowerShell Remoting settings...
Boxstarter: Testing remoting access on neptune10.tam.local...
Boxstarter Version 2.11.0
(c) 2018 Chocolatey Software, Inc, 2012 - 2018 Matt Wrock. https://boxstarter.org

Boxstarter: Configuring local PowerShell Remoting settings...
Boxstarter: Configuring CredSSP settings...
Boxstarter: Testing remoting access on neptune10.tam.local...
Boxstarter: Remoting is accessible on neptune10.tam.local
Boxstarter: Copying Boxstarter Modules and LocalRepo packages at C:\ProgramData\Boxstarter to C:\Users\ADMINI~1\AppData\Local\Temp\2 on neptune10.tam.local...
Boxstarter: Running remote install...
[NEPTUNE10]Boxstarter: Installing package sublimetext3
[NEPTUNE10]Boxstarter: Disabling Automatic Updates from Windows Update
[NEPTUNE10]++ Boxstarter starting Calling Chocolatey to install sublimetext3. This may take several minutes to complete...
[NEPTUNE10]Boxstarter: Error from Chocolatey:

Message                     : Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path
                              'C:\Users\TaniumSvc\AppData\Local\Temp\Boxstarter\boxstarter.chocolatey\chocolatey\log4net.dll'
                              because it does not exist."
ParameterName               : Path
ParameterType               : System.String[]
TypeSpecified               : System.String[]
ErrorId                     : ParameterBindingFailed
Line                        : 15
Offset                      : 28
CommandInvocation           : System.Management.Automation.InvocationInfo
ErrorRecord                 : Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path
                              'C:\Users\TaniumSvc\AppData\Local\Temp\Boxstarter\boxstarter.chocolatey\chocolatey\log4net.dll'
                              because it does not exist."
WasThrownFromThrowStatement : False
Data                        : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
InnerException              : System.Management.Automation.SetValueInvocationException: Exception setting "Path": "Cannot find
                              path
                              'C:\Users\TaniumSvc\AppData\Local\Temp\Boxstarter\boxstarter.chocolatey\chocolatey\log4net.dll'
                              because it does not exist." ---> System.Management.Automation.ItemNotFoundException: Cannot find
                              path
                              'C:\Users\TaniumSvc\AppData\Local\Temp\Boxstarter\boxstarter.chocolatey\chocolatey\log4net.dll'
                              because it does not exist.
                                 at System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean
                              allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider, CmdletProviderContext
                              context)
                                 at System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path,
                              CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance)
                                 at System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String path,
                              Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider& providerInstance)
                                 at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String
                              path, Boolean allowNonexistingPaths, CmdletProviderContext context, ProviderInfo& provider,
                              CmdletProvider& providerInstance)
                                 at System.Management.Automation.LocationGlobber.GetGlobbedProviderPathsFromMonadPath(String
                              path, Boolean allowNonexistingPaths, ProviderInfo& provider, CmdletProvider& providerInstance)
                                 at Microsoft.PowerShell.Commands.AddTypeCommandBase.set_Path(String[] value)
                                 at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name, Object
                              value, CompiledCommandParameter parameterMetadata)
                                 --- End of inner exception stack trace ---
                                 at System.Management.Automation.ReflectionParameterBinder.BindParameter(String name, Object
                              value, CompiledCommandParameter parameterMetadata)
                                 at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal
                              parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
TargetSite                  : Void CheckActionPreference(System.Management.Automation.Language.FunctionContext, System.Exception)
StackTrace                  :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext
                              funcContext, Exception exception)
                                 at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                                 at
                              System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                              frame)
                                 at
                              System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                              frame)
                                 at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                                 at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                                 at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke
                              clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1
                              variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input,
                              Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
                                 at System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
                                 at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCh
                              eck(Action action)
                                 at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope,
                              ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis,
                              Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1
                              variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
                                 at System.Management.Automation.ScriptBlock.InvokeUsingCmdlet(Cmdlet contextCmdlet, Boolean
                              useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input,
                              Object scriptThis, Object[] args)
                                 at Microsoft.PowerShell.Commands.ForEachObjectCommand.ProcessRecord()
                                 at System.Management.Automation.CommandProcessor.ProcessRecord()
HelpLink                    :
Source                      : System.Management.Automation
HResult                     : -2146233087

[NEPTUNE10]++ Boxstarter finished Calling Chocolatey to install sublimetext3. This may take several minutes to complete... 00:00:00.8805039
[NEPTUNE10]Boxstarter: Restore Automatic Updates from Windows Update

Errors       : {$null, Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path
               'C:\Users\TaniumSvc\AppData\Local\Temp\Boxstarter\boxstarter.chocolatey\chocolatey\log4net.dll' because it does
               not exist."}
ComputerName : neptune10.tam.local
Completed    : True
FinishTime   : 7/30/2018 7:48:56 PM
StartTime    : 7/30/2018 7:48:50 PM

Boxstarter: Rolling back remoting settings changed by Boxstarter...

PS C:\>

**Comment by flcdrg** [comment]
This looks to be the same problem as #324? If so, it should be addressed in the next release.

**Comment by rajganeshp** [comment]
Thanks for the update. Any workaround for this issue?

**Comment by flcdrg** [comment]
RDP to the VM and run Boxstarter directly?

Alternatively, you could try using an older version of Boxstarter to see if that helps.
