### ISSUE TITLE
Usage of boxstarter from network share failed

### ISSUE THREAD

**Issue by SheGe** [chocolatey/boxstarter#327]
Hi,

Usage of boxstarter from network share from the latest Win 10 Pro failed probably because the problems with loading the `*.dll` files from Network Share.

```console
Add-Type : Could not load file or assembly
'file://\\***\BoxShare/boxstarter.chocolatey/chocolatey/log4net.dll' or one of its
dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
At \\***\BoxShare\Boxstarter.Chocolatey\invoke-chocolatey.ps1:15 char:13
+             Add-Type -Path $_
+             ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.AddTypeCommand
```

Steps to reproduce:
1. Using the script below install latest boxstarter on network share host system (xxx), the command found in documentation [here](https://boxstarter.org/InstallBoxstarter)
    ```powershell
    . { iwr -useb https://boxstarter.org/bootstrapper.ps1 } | iex; get-boxstarter -Force
    ```
1. From network share host system execute this command to create the network share, the command found in documentation [here](https://boxstarter.org/InstallingPackages)
    ```powershell
    Set-BoxstarterShare BoxShare
    ```
1. ~~Create the file with content as follow in this location `$env:TEMP\install.ps1` on the fresh Win 10 VM:~~
    *Usage of the powershell script is not allowed, because Read Only permission on the share - usage of existing package is required*
    ```powershell
    Set-WindowsExplorerOptions -EnableShowHiddenFilesFoldersDrives -EnableShowFileExtensions
    ```

1. From the same Win 10 VM execute the command below from powershell console running as administrator:
    ```powershell
    & \\xxx\BoxShare\BoxStarter MyPackage
    ```

Full console output:
```console
Boxstarter: Installing package C:\Users\Admin\AppData\Local\Temp\install.ps1
Boxstarter Version 2.11.0
(c) 2018 Chocolatey Software, Inc, 2012 - 2018 Matt Wrock. https://boxstarter.org

Please type CTRL+C or close this window to exit Boxstarter if you do not want to risk a reboot during this Boxstarter install.

Boxstarter may need to reboot your system.
Please provide your password so that Boxstarter may automatically log you on.
Your password will be securely stored and encrypted.
Autologon Password: ******************
Boxstarter: Successfully authenticated password.
Boxstarter: Disabling Automatic Updates from Windows Update
Boxstarter: Restore Automatic Updates from Windows Update
Add-Type : Could not load file or assembly
'file://\\xxx\BoxShare/boxstarter.chocolatey/chocolatey/log4net.dll' or one of its
dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
At \\xxx\BoxShare\Boxstarter.Chocolatey\invoke-chocolatey.ps1:15 char:13
+             Add-Type -Path $_
+             ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.AddTypeCommand
```

Do you have any suggestions how resolve this issue?

Thanks

**Comment by SheGe** [comment]
Might be, but from my understanding of this issue this can be related to .NET itself as described: [here](https://stackoverflow.com/questions/19957161/add-type-load-assembly-from-network-unc-share-error-0x80131515), more about loading resources from remote sources in [Microsoft Documentation](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/loadfromremotesources-element). Changing these files temporary - like auto login, or Windows Updates should help.

**Comment by SheGe** [comment]
Might be, but from my understanding of this issue this can be related to .NET itself as described: [here](https://stackoverflow.com/questions/19957161/add-type-load-assembly-from-network-unc-share-error-0x80131515), more about loading resources from remote sources in [Microsoft Documentation](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/runtime/loadfromremotesources-element). Changing these files temporary - like auto login, or Windows Updates should help.

**Comment by flcdrg** [comment]
Can you confirm if file://\\xxx\BoxShare/boxstarter.chocolatey/chocolatey/log4net.dll exists?

If it doesn't, then I think this is #324. If not, then it probably is different.

**Comment by SheGe** [comment]
Yes, all files exist. Today I've investigated this more and the problem seems to be related to the way how assemblies are loading in `invoke-chocolatey.ps1` script.
Setting the environment variable `[Environment]::SetEnvironmentVariable("TestingBoxstarter", $true)` before triggering boxstarter resolved my issue.

```powershell
if($env:TestingBoxstarter) {
    Write-BoxstarterMessage "loading choco bytes" -Verbose
    [System.Reflection.Assembly]::Load([io.file]::ReadAllBytes($_))
}
else {
    Write-BoxstarterMessage "loading choco from path" -Verbose
    Add-Type -Path $_
}
```
