### ISSUE TITLE
Feature Request - Guest VMs

### ISSUE THREAD

**Issue by rajganeshp** [chocolatey/boxstarter#332]
This may not be the right place to ask, but I wanted to check anyway. 

Installing guest windows VMs in Hyper-v is not hard with Powershell automation. Is there a way to automate linux OS installation in Hyper-v using Chocalatey/Boxstarter or any other tools? Looking for something similar to Vagrant where can bring in multiple Linux guest VMs in Hyper-v. 

Thanks for your help.
Raj

**Comment by mwallner** [comment]
hey @rajganeshp  - you're right - not quite the right place 😄 

have you heard of Packer? - https://www.packer.io/ 
and/or vagrant? - https://www.vagrantup.com/

- that's what I use

**Comment by rajganeshp** [comment]
thanks for the links
