### ISSUE TITLE
Elevated PowerShell window is left open after installation

### ISSUE THREAD

**Issue by joaocgreis** [chocolatey/boxstarter#339]
### What You Are Seeing?

Boxstarter opened an elevated PowerShell window to install a script. After the script installation the window was left open.

This might be confusing for users less familiar with Windows in general ("Did it already finish? Or doing something in the background? Can I close this?"). This might also be considered a security issue: scripts can take a long time to run, users may leave the computer unattended and the elevated console might be used by someone else.

### What is Expected?

The window should pause at the end to allow reading the console output, but then exit without giving users a chance to use the console (something similar to https://github.com/chocolatey/boxstarter/blob/262f07e81d8f1dc3a20ac7530f35d241bd9b3c80/Boxstarter.Bootstrapper/Cleanup-Boxstarter.ps1#L38).

### How Did You Get This To Happen? (Steps to Reproduce)

Run a script without Admin privilege in Windows 10 (mine is 10.0.17134.228).

**Comment by pauby** [comment]
PR #340 was merged.
