### ISSUE TITLE
Blue screen of death when attempting to install windows updates using Install-WindowsUpdate

### ISSUE THREAD

**Issue by whiggs** [chocolatey/boxstarter#342]
### What You Are Seeing?
I have a test vm that I am using to show boxstarter's useful capabilities in order to use it in our environment.  It is a relatively simple package: installs some modules from powershell gallery, installs some applications using chocolatey, and is supposed to install available windows updates.  However, when it gets to the part where boxstarter displays that it is actually updating windows, twice now, I have gotten a blue screen of death with the error code IRQL_NOT_LESS_OR_EQUAL.  I have attached a zip file containing the dump files and the analysis of these dump files using both Resplendence Software's [WhoCrashed](http://www.resplendence.com/whocrashed) and Nirsoft's [BlueScreenView](http://www.nirsoft.net/utils/blue_screen_view.html).  According to what I am seeing, the dumps indicate that the issue is being caused by a software bug.  Also, the guest vm os on which the boxstarter package is being run is Windows Server 2016 Datacenter edition.

### What is Expected?
The vm to not blue screen

### How Did You Get This To Happen? (Steps to Reproduce)
Run "install-boxstarterpackage -packagename "https://gist.githubusercontent.com/whiggs/c705a10399bdc75d5c3f50151e63501d/raw/7d0fb0c279d7783752dee9892afd482722324b3d/upboxsta.ps1"

### Output Log

<details>
Not sure how to provide this, as I ran the command with the two arguments in the powershell console, but boxstarter seemed to treat the first parameter as if it were a remote machine that it was trying to connect to.  I looked at the log in the %USERPROFILE%\appdata\local\boxstarter directory and saw that the latest log entry was "installing windows update 1 out of 3" with nothing beyond that though.

</details>

**Cannot attach the zip file containing dump information, so I will create a link to it below:**
https://acuitybrandsinc-my.sharepoint.com/:u:/g/personal/wmh02_acuitysso_com/EbpiItuLu0hDqq_S3ghe2dkBHZjEE2JDpic1afenadIZPg?e=Yd4zOd

**Comment by whiggs** [comment]
**Was it [the vm] a vanilla os before running the boxstarter script?**
Yes and no.  Yes the operating system was installed using installation media obtained directly from Microsoft, but I had also created an unattend answer file to automate several aspects of the operating system install and configuration (which I see no reason to think would be the cause of any issue), including joining a domain, adding users to certain local groups, and, upon logging in for the first time, installing boxstarter and running the script which caused the bluescreen.  My goal was to automate everything from the time the installation media is booted to the end of the boxstarter script.  Didn't end too well.....

**Comment by mwrock** [comment]
I'd also suggest trying with something like https://www.powershellgallery.com/packages/PSWindowsUpdate/2.0.0.4 since that likely uses the similar or same apis.

**Comment by pauby** [comment]
No response in some time so issue is stale and therefore closing. We can always reopen this in the future if needed.
