### ISSUE TITLE
[Proposal] Naming standards for Boxstarter public functions

### ISSUE THREAD

**Issue by flcdrg** [chocolatey/boxstarter#343]
Boxstarter has historically provided some useful PowerShell functions for use in Boxstarter scripts. There vave been a number of reported problems with these functions conflicting (or superceding) similarly named functions provided by other PowerShell modules. 

If there was a way to allow PowerShell to keep different functions with the same name separate and not conflict, then that would be great. If there isn't a way to do that that works with Boxstarter, then the next best thing may be to impose a naming standard for all of Boxstarter's functions.

This pattern should help reduce the chance of name collisions:

`[Verb]-Boxstarter[FunctionName]`

_Examples:_

Current | New
---- | -----
Enable-RemoteDesktop | Enable-BoxstarterRemoteDesktop
Install-WindowsUpdate | Install-BoxstarterWindowsUpdate
Set-WindowsExplorerOptions | Set-BoxstarterWindowsExplorerOptions

If this proposal went ahead, then we'd need to consider how to introduce it - make it a breaking change, or provide both for a period of time (maybe with warnings for using the old names), or other options.

Related issues:

- https://github.com/chocolatey/boxstarter/issues/293 (including this comment) https://github.com/chocolatey/boxstarter/issues/293#issuecomment-348729620
- https://github.com/jberezanski/ChocolateyPackages/issues/53)

**Comment by pauby** [comment]
Best practice for PowerShell is to have a 2 - 3 letter prefix for the Noun in a PowerShell module function (the Azure team (-AzureAD) and PowerBi team (-PowerBI I believe)) aside. The problem with that is we already have the majority of Boxstarter functions have the Boxtstarter prefix. So I'm not sure what to do there - do we draw a line in the sand and start using a new prefix or do we continue with -Boxstarter.

The primary reason for trying to stick with 2 - 3 characters is that people are typing those over and over again at the command line so the less you make them type the happier everybody is. However Boxstarter is aimed at (build) scripts and not the command line. You write a script once and it's done. So that rule is not so important. So I've kind of talked myself out of that. But hey, if somebody else asks the question at least we have an answer ...

You can of course use the Boxstarter module name in the function call to stop the conflicts but I agree that's really not used widely.

**Comment by smartmarmot** [comment]
Actually I like @flcdrg 's proposal.
And to be honest I see quite a few function that are already adopting the naming convention proposal:

`[Verb]-Boxstarter[FunctionName]`

Probably is time to address the normalization or refactoring if you like. I am only concerned by all the amount of code that is already using the current naming.
Here is an extract of the current situation.

Compliant | Non Compliant
------------ | -------------
Get-BoxstarterConfig | |
| | Resolve-VMPlugin
| |Get-PackageRoot

This for sure will break the compatibility that is something I don't like. BUUUT is definitely better address this issue sooner than later.

**Comment by pauby** [comment]
> This for sure will break the compatibility that is something I don't like. BUUUT is definitely better address this issue sooner than later.

We can just add aliases for the original function names and gradually phase them out if necessary but make sure all future code complies.

**Comment by pauby** [comment]
Can we get a consensus around this so we can get to moving with #341?

I agree with @flcdrg [proposal](https://github.com/chocolatey/boxstarter/issues/343#issue-358846487) as the sensible way to go. And we create aliases for those functions that are renamed? After a period of time (can't we agree v3.0 initially and then have a discussion at that time to see if it's good at that time) we phase out the aliases?

**Comment by pauby** [comment]
We have PR #341 waiting to decide on what naming convention to use. Can we gather consensus on this? I agree with @flcdrg [proposal](https://github.com/chocolatey/boxstarter/issues/343#issue-358846487) using `[Verb]-Boxstarter[Noun]` going forward and all functions should adhere to that:

Current | New
---- | -----
Enable-RemoteDesktop | Enable-BoxstarterRemoteDesktop
Install-WindowsUpdate | Install-BoxstarterWindowsUpdate
Set-WindowsExplorerOptions | Set-BoxstarterWindowsExplorerOptions

This will apply to all new functions going forward. We will have a cleanup of those existing functions in the future to rename them, deprecate the old names but leave aliases in place to continue so we don't break anything! In a future release we can remove the dprecated function names (although there is no real harm in leaving them there, [clashes aside](https://github.com/chocolatey/chocolatey-coreteampackages/pull/1129).

/cc @flcdrg @mwallner @gep13

**Comment by mwallner** [comment]
I very much like the proposed `[Verb]-Boxstarter[Noun]` naming scheme, as long as we'll introduce aliases for the existing commands, that is at least until the next "major release".
