### ISSUE TITLE
Allow no password when prompted for password

### ISSUE THREAD

**Issue by crutkas** [chocolatey/boxstarter#348]
### What You Are Seeing?
Creating a script for https://github.com/Microsoft/windows-dev-box-setup-scripts and have a VM i'm using for testing.  The VM doesn't have a password.  The cmd won't accept no password as an option.

![image](https://user-images.githubusercontent.com/1462282/46237261-2a4bdd80-c338-11e8-9ca7-2e108c2938a9.png)

### What is Expected?

allow no password to be accepted

### How Did You Get This To Happen? (Steps to Reproduce)

Run script from https://github.com/Microsoft/windows-dev-box-setup-scripts

**Comment by flcdrg** [comment]
Probably relates to #338 too
