### ISSUE TITLE
Forced installation upon boot.

### ISSUE THREAD

**Issue by WizardLink** [chocolatey/boxstarter#354]
I know this is not exactly in chocolatey's end (I use* chocolatey myself) but a program I use has gave me the option to install boxstarter which I ticked off but it somehow started, I did not really mind but it restarted my system several times and anytime I boot it opens a new powershell instance, I would like to know how I would move on to remove this completely. I have tried removing the ProgramData folder and AppData but I did not find anything else anywhere.

_\* - Sorry it is pretty late and I am tired._

**Comment by flcdrg** [comment]
The normal way of installing Boxstarter is via Chocolatey, so I'd try using `choco uninstall`

Are you able to say what the program was that had the option of installing Boxstarter?

**Comment by WizardLink** [comment]
I am running all my recent wizards but I am not entirely sure which had that option. I have tried indeed using chocolatey to uninstall but `choco list` gives me 0 packages installed and this Powershell instance keeps popping in every login.

**Comment by WizardLink** [comment]
I found where the issue was, I should have thought about it earlier. 
`C:\Users\<USER>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\boxstarter-post-restart.bat`

About the program that installed boxstarter, unfortunately, I have not found it. Perhaps it was not even optional and I misread.
