### ISSUE TITLE
Boxstarter keep restarting my windows 7 computer in an infinite loop

### ISSUE THREAD

**Issue by aflext** [chocolatey/boxstarter#356]
I install node.js and checked the 'tools' option and the node.js installer installed the chocolately, and then the install program keep restarting my computer in an infinite loop.

Everytime the computer starts, there is a `cmd` prompt shows 'Boxstarter disable auto update of windows blablah', i even can't have time to capture the screen...

So, does anybody know this ? How to stop or delete the auto restart program ?

**Comment by flcdrg** [comment]
To clarify, did you install Node using Boxstarter? If so, what command/s did you use?

**Comment by aflext** [comment]
@flcdrg i just download `node.js` exe to install and check the install `install windows build tools ` option and it install chocolately.

**Comment by ian-at-drs** [comment]
Me too - with Windows 10. I killed the power-shell when it appeared after the third or fourth reboot, which stopped the cycle (for now).

**Comment by flcdrg** [comment]
I didn't know that Node.js had that option. Looks like it relates to https://github.com/nodejs/node/blob/master/tools/msvs/install_tools/install_tools.bat.

**Comment by MuathKefayah** [comment]
bro ... did you solve your problem? , because I have the same problem recently. if yes, please send me the solution.

thanks in advance.

**Comment by pauby** [comment]
@MuathKefayah See [here](https://github.com/chocolatey/boxstarter/issues/356#issuecomment-430093387).

**Comment by pauby** [comment]
This doesn't appear to be a Boxstarter issue but a Node 'build tools` issue?

**Comment by MuathKefayah** [comment]
@pauby  Honestly I am so far not sure what exactly the problem is, since I am modern dealing with the Node.js  , But the problem seems to be related to Boxstarter shell , Since I can not continue in widows process unless I close Boxstater shell from task manager.

**Comment by pauby** [comment]
@MuathKefayah @ian-at-drs @aflext Can somebody outline the EXACT steps they took so we can reproduce this problem?

**Comment by ian-at-drs** [comment]
I downloaded node-v10.12.0-x64.msi from https://nodejs.org/dist/v10.12.0/node-v10.12.0-x64.msi and installed it. Like @MuathKefayah I ticked the "Automatically install the necessary tools..." option - see screen shot. This option installs Boxstarter and Chocolatey. This was my first install of Node.js and these two other products.
![node-v10 12 0-x64 install](https://user-images.githubusercontent.com/44185125/47047770-116c7480-d1e0-11e8-8ecf-f0e108e67045.png)
I have uninstalled Node.js, and Boxstarter is still trying to reboot my PC each time I start it up. I have to kill off the shell window before it initiates the reboot. I will search the web for assistance about this.

**Comment by ian-at-drs** [comment]
Thanks @pauby! I found boxstarter-post-restart.bat and have deleted it. I will also remove "C:\ProgramData\boxstarter" and everything below it.

**Comment by pauby** [comment]
Try removing it with Chocolatey first.

**Comment by aflext** [comment]
I  have tried to uninstall the boxstarter with Chocolatey  but got failed message like `boxstarter not installed`. So i delete the folder  `C:\ProgramData\boxstarter` and then restart my PC and i got a CMD prompt showing red messages(i guess because i have deleted the boxstarter) and then the CMD prompt auto close itself without restarting my PC.

**Comment by ian-at-drs** [comment]
Hi @aflext, try following @pauby's advice and look in C:\Users\YOURUsername\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup for the boxstarter-post-restart.bat file, and delete that too.

**Comment by MuathKefayah** [comment]
Thanks a lot everyone, everything is good after taking your advice seriously

**Comment by eromoe** [comment]
Happen on windows 10 too .

**Comment by DavidEscamilla** [comment]
Hi everyone!

Launch "Startup Tasks" from windows start menu and toggle off "boxstarter-post-restart.bat"
