### ISSUE TITLE
NodeJS induced install failed - how to revert?

### ISSUE THREAD

**Issue by oskargustafsson** [chocolatey/boxstarter#357]
I'm not going to stick to the proposed template for reporting issues, but please bear with me.

I installed NodeJS 8 for Windows, using their standard installer. It asked me if I wanted to also install Chocolatey/Boxstarter, in order to be able to build C/C++ packages. I checked "yes", naively not even looking up what these things are.

After the NodeJS installation finished, some script started installing Chocolatey and Boxstarter. After a couple of restarts and lots of scary messages about disabling Windows Update and UAC, the installation failed (I think) with the following message:

```
Chocolatey reported an unsuccessful exit code of 3010. See C:\Users\oskar\AppData\Local\Boxstarter\boxstarter.log for details.
+ Boxstarter finished Calling Chocolatey to install . This may take several minutes to complete... 00:08:56.0752760
+ Boxstarter finished Calling Chocolatey to install . This may take several minutes to complete... 00:08:56.0752760
Only an exit code of non-zero will fail the package by default. Set
 `--failonstderr` if you want error messages to also fail a script. See
 `choco -h` for details.
 The install of tmpd8eb.tmp was successful.
  Software installed to 'C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Phone Sirep\8.1\'

Chocolatey installed 1/1 packages. 0 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Chocolatey : Chocolatey reported an unsuccessful exit code of 3010. See
C:\Users\oskar\AppData\Local\Boxstarter\boxstarter.log for details.
At C:\ProgramData\boxstarter\BoxStarter.Chocolatey\Invoke-ChocolateyBoxstarter.ps1:199 char:5
+     Chocolatey install $bootstrapPackage -source $source -force:$forc ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,chocolatey

++ Boxstarter finished Calling Chocolatey to install tmpD8EB.tmp. This may take several minutes to complete... 00:09:05.8946195
True
Boxstarter: Restore Automatic Updates from Windows Update
Boxstarter: Enabling UAC
```

The log file (boxstarter.log) contains 600kb of uninteresting logs. The most relevant line, which is repeated a few times is:
```
Error getting parent process
```
Let me know if you need the full log.

Now, I can't help but to feel that my computer has been a bit violated, and my questions are:
- What did the install script do, and where can I find it, to read it myself? All those restarts indicate that it did some low level system alterations.
- What exactly did it install? Chocolatey, Boxstarter, VS modules, Python, what else?
- How do I undo all the things it did? E.g. what files do I remove, do I need to restore BIOS virtualization settings, what environment variables do I need to remove/reset?

**Comment by pauby** [comment]
Related to #356 ?

**Comment by gep13** [comment]
I am fairly sure I know what was going on here. I have been collecting some information together and hoping to put it all together in a write up tonight.

**Comment by BrunoWinck** [comment]
Arrived here with same problem. My goal was to compile some apps, so I naively thought it will chain with downloading libraries and a few scripts. The messages in command line are way too long to be read. Remember it's just an update of nodejs. Windows rebooted without warning ( I had a project open and other things), and again rebooted. Finally failed as above. Messages are way too long and fast to be read. 
This was for Nodejs 10.13.0 , on Windows 10 pro.
I think the checkbox was deceptive as per consequences. It should be a completely different package or with several messages box.
I felt trapped like in the times of old Microsoft cascades of updates, KB etc.

**Comment by pauby** [comment]
@BrunoWinck You might want to add your voice over at https://github.com/nodejs/node/issues/23838 to help those guys out.
