### ISSUE TITLE
windows10 reboots constantly

### ISSUE THREAD

**Issue by lesper** [chocolatey/boxstarter#365]
![image](https://user-images.githubusercontent.com/22119288/48300811-7b95e200-e51e-11e8-9d4f-bd4af8822dc1.png)

![image](https://user-images.githubusercontent.com/22119288/48300822-99634700-e51e-11e8-9353-3e8f71eaa675.png)

-->
windows10 reboots constantly.

**Comment by mwallner** [comment]
hey @lesper, thanks for submitting this issue.
on order to be able to help, we'll need some additional info:

* Boxstarter Version (`choco list boxstarter -lo`)
* Windows Build/Version (`winver`)
* PowerShell Version (`$PSVersionTable`)
* what package did you install last before it came to this reboot loop 

Did you resolve the problem by removing that .bat file from your autostart folder?
Did Boxstarter continue to pop-open and try to finish it's outstanding package install?

**Comment by lesper** [comment]
I installed it with node.js.

and boxstarter broke my Win10 Administrator Privileges.
windows 10 UAC ↓↓↓↓↓↓
Makes my Windows10 get Administrator Privileges everywhere.



Boxstarter version ： 
![image](https://user-images.githubusercontent.com/22119288/48301870-755c3180-e52f-11e8-8740-766955d9f152.png)

![image](https://user-images.githubusercontent.com/22119288/48301871-81e08a00-e52f-11e8-9140-e121aac16c9b.png)


![image](https://user-images.githubusercontent.com/22119288/48301874-8b69f200-e52f-11e8-823c-5f2a7f11617a.png)

**Comment by mwallner** [comment]
hey,
sorry to hear this - but there's a known issue concerning Node.js-Setup + Boxstarter.

as @gep13 explained in this post: https://github.com/nodejs/node/issues/23838#issuecomment-434601124

take a look at the links in that comment, especially this one: https://github.com/chocolatey/boxstarter/issues/357#issuecomment-431705029

hope this helps you getting things fixed - I'm closing this issue for now as it's a duplicate.
please let me know if you've got additional questions.
