### ISSUE TITLE
Run Boxstarter in deployment audit mode

### ISSUE THREAD

**Issue by wjk** [chocolatey/boxstarter#374]
Is it possible to run Boxstarter when Windows is booted into [deployment audit mode](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/boot-windows-to-audit-mode-or-oobe)? This would help me when setting up a new retail PC I just purchased, in that I can run a subset of Boxstarter scripts ([those in this file, in particular](https://github.com/Microsoft/windows-dev-box-setup-scripts/blob/master/scripts/RemoveDefaultApps.ps1)) before I boot to the desktop for the first time. I understand that per the Microsoft docs computers booted in audit mode should not be connected to the Internet, nor should updates be installed; I would use fully offline Choco packages mounted from a thumb drive and avoid using the update cmdlets.

I'm just wondering if this is possible at all, and if so, what restrictions should I be aware of? (Unfortunately, I don't have a spare copy of Windows 10 I can test with at the moment.) Any and all advice would be appreciated. Thanks so much!

**Comment by mwallner** [comment]
Hey @wjk 
it is possible to use boxstarter and chocolatey fully offline, given that you've also got all the packages you want to install stored locally.
I actually use this a lot.

see https://boxstarter.org/InstallingPackages - scroll down to "Running an Install from a network share or external media" 
after you've run
```
Copy-Item $Boxstarter.BaseDir <somedrive>:\boxstarter -Recurse
```

you can use the command 
```
<somedrive>:\boxstarter\Boxstarter <package>
```
to install any package that's available offline (by default boxstarter tries to pull from chocolatey.org as well as the `BuildPackages` directory you should see at `<somedrive>:\boxstarter\BuildPackages`)

**Comment by pauby** [comment]
@wjk Did this resolve your issue?

**Comment by wjk** [comment]
@pauby Yes it did. Thanks!
