### ISSUE TITLE
Document uninstall process

### ISSUE THREAD

**Issue by pauby** [chocolatey/boxstarter#378]
Given the recent 'issues' with NodeJs using Boxstarter we need to have some documentation around uninstalling Boxstarter.

See #371, #368 and #336 (and perhaps others).

**Comment by jtflynnz** [comment]
looks like a good writeup was done in #357  (specifically [this post](https://github.com/chocolatey/boxstarter/issues/357#issuecomment-431705029)); could be a good starting point.
