### ISSUE TITLE
'RebootOk' cannot be found on this object.

### ISSUE THREAD

**Issue by jmlucjav** [chocolatey/boxstarter#380]
### What You Are Seeing?

I run a simple script that contains:

> $Boxstarter.RebootOk=$true # Allow reboots?
> choco list --lo

I run it like this:

`
powershell -ExecutionPolicy Bypass "& ""boxstarter.test.ps1"""
`

I get:

> The property 'RebootOk' cannot be found on this object. Verify that the property exists and can be set.
> At boxstarter.test.ps1:4 char:1
> + $Boxstarter.RebootOk=$true # Allow reboots?
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
>     + FullyQualifiedErrorId : PropertyNotFound

the choco packages get listed fine.
I have Boxstarter 2.12.0, same was happening with 2.8

### What is Expected?
runs fine, lists choco packages

### How Did You Get This To Happen? (Steps to Reproduce)
- open cmd as admin
- run command line above

My hosts is Microsoft Windows [Version 10.0.17763.134]

**Comment by mwallner** [comment]
hey @jmlucjav, 
the way you're invoking your script you're missing the Boxstarter PowerShell module.

you can resolve your problem by either:
* calling the script directly via Boxstarter Shell.
* adding `Import-Module Boxstarter.Chocolatey` at the top of your script.

(following should work:)
```
Import-Module Boxstarter.Chocolatey
$Boxstarter.RebootOk=$true # Allow reboots?
choco list --lo
```
- you can call this script just like you did before: `powershell -ExecutionPolicy Bypass "& ""D:\boxstarter.test.ps1""" `

**Comment by jmlucjav** [comment]
excellent, tried and of course it works. 

The first script I created did not need this import, I believe, and since then I use it on new pcs, I see these failures but never got to the bottom of it as the rest was working, but this brings closure. Thanks!!!
