### ISSUE TITLE
Unable to have package run successfully on reboot

### ISSUE THREAD

**Issue by TrevorWesterdahl** [chocolatey/boxstarter#393]
### What You Are Seeing?
I am trying to create a package that will make a few adjustments to windows and install Windows updates. As you know, updates can take several reboots. I created a Powershell script (see appropriate section), created a package for it, built the package, and then install the package using appropriate credentials. Upon first use, it seems to work. Windows updates are run, installed, and a reboot occurs. However, Boxstarter does not log back in and continue. I log in and a Boxstarter shell opens but it does nothing. I check Windows updates and there are more updates available. If I try to run the install again, it says it installed and completed, but it actually ran nothing (my script creates a log and there is no log)

My intention is to merge this into all the setup I already have working with Chocolately (setting roles and features, installing IIS, adding sites, app pools, installing apps, etc). 

What am I doing wrong?

NOTE: I am worried that I see a message that Windows Updates are disabled by Boxstarter. Perhaps that has something to do with it? (see attached image below).

### What is Expected?
I expect Boxstarter to apply Windows updates, reboot, check for more updates and repeat until there are no more updates to apply.

### How Did You Get This To Happen? (Steps to Reproduce)
Below is the code/script for  'UpdateWindows.ps1' within package. There is a simple nuspec file and the nupkg file that is autogenerated. Its just one script file (shown below)

```powershell
function global:Write-Notepad
(
    [string] $Message,
    [string] $ForegroundColor = 'Gray'
)
{
    Process
    {
        if($_){ Write-Host "$_`r" }
    }
    End
    {
        if($Message){ Write-Host "$Message`r" -ForegroundColor $ForegroundColor }
    }
}

try {
	#get-date -Format g
	Start-Transcript -Path "C:\temp\UpdateWindowsLog.log" -Append
	$msg = ("[{0}] {1}" -f (get-date -Format g), "Beginning 'Update Windows' script")
	Write-Notepad $msg
	$msg = ("[{0}] {1}" -f (get-date -Format g), "Setting Execution policy")
	Write-Notepad $msg
	Set-ExecutionPolicy Unrestricted -Force
	$msg = Write-Notepad ("[{0}] {1}" -f (get-date -Format g), "Importing Boxstarter and Chocolately modules")
	Write-Notepad $msg
	Import-Module Boxstarter.Chocolatey
	$msg = ("[{0}] {1}" -f (get-date -Format g), "Disabling UAC")
	Write-Notepad $msg
	Disable-UAC
	#Write-Notepad ("[{0}] {1}" -f (get-date -Format g), "Disabling Microsoft Update")
	#Disable-MicrosoftUpdate
	$msg = ("[{0}] {1}" -f (get-date -Format g), "Applying MS Explorer options")
	Write-Notepad $msg
	Set-ExplorerOptions -showHiddenFilesFoldersDrives -showProtectedOSFiles -showFileExtensions
	$msg = ("[{0}] {1}" -f (get-date -Format g), "Enabling Remote Desktop")
	Write-Notepad $msg
	Enable-RemoteDesktop
	$msg = ("[{0}] {1}" -f (get-date -Format g), "Disabling IE Enhanced Security")
	Write-Notepad $msg
	Disable-InternetExplorerESC
	$msg = ("[{0}] {1}" -f (get-date -Format g), "Enabling Windows Update")
	Write-Notepad $msg
	Enable-MicrosoftUpdate
	$msg = ("[{0}] {1}" -f (get-date -Format g), "Installing Windows Updates")
	Write-Notepad $msg
	Install-WindowsUpdate -AcceptEula -Criteria "IsInstalled=0 and Type='Software' and BrowseOnly=0"
	# Install-WindowsUpdate -Criteria "IsHidden=0 and IsInstalled=0 and Type='Software' and BrowseOnly=0 and Type='Driver'"
	$msg = ("[{0}] {1}" -f (get-date -Format g), "Enabling UAC")
	Write-Notepad $msg
	Enable-UAC
	$msg = ("[{0}] {1}" -f (get-date -Format g), "'Update Windows' script completed.")
	Write-Notepad $msg
	Stop-Transcript
} catch {
	$msg = ("[{0}] {1} {2}" -f (get-date -Format g), "WARNING!!! An unexpected error ocurred!",$($_.Exception.Message))
	Write-Notepad $msg
    throw $_
}
```

Simplified code if there was no logging:

```powershell
try {
	Set-ExecutionPolicy Unrestricted -Force
	Import-Module Boxstarter.Chocolatey
	Disable-UAC
	Enable-RemoteDesktop
	Disable-InternetExplorerESC
	Enable-MicrosoftUpdate
	Install-WindowsUpdate -AcceptEula -Criteria "IsInstalled=0 and Type='Software' and BrowseOnly=0"
	Enable-UAC
} catch {
    throw $_
}
```

### Output Log
No logs are generated in the Boxstarter log directory. See attached image of trying to rerun the installer. 
![Boxstarter Example](https://user-images.githubusercontent.com/23147347/55906310-96d24f80-5b99-11e9-88c8-89921dddd360.jpg)

**Comment by pauby** [comment]
If all you have in your package is a `.nuspec` file and `UpdatesWindows.ps1` nothing will happen. 

Rename `UpdatesWindows.ps1` to `chocolateyInstall.ps1` in your package or call `Install-BoxstarterPackage -PackageName UpdateWindows.ps1` where Boxstarter will create a package for you.

**Comment by TrevorWesterdahl** [comment]
I did run Install-BoxstarterPackage. First I did this:

New-BoxstarterPackage -Name "UpdateWindows" -Description "Applies windows updates and reboots as necessary" -Path "C:\temp\UpdateWindows"
Invoke-BoxstarterBuild UpdateWindows

Then I ran this:
$User = "NWLIC\domainuser"
$PWordFile = "C:\Temp\domainuser.pwd"
$KeyFile = "C:\temp\AES.key"
$Key = Get-Content $KeyFile
$PWord = (Get-Content $PWordFile | ConvertTo-SecureString -key $Key )
$cred=New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $User, $PWord
Install-BoxstarterPackage -PackageName UpdateWindows -Credential $cred

**Comment by TrevorWesterdahl** [comment]
No response?

**Comment by pauby** [comment]
What is the contents of your UpdateWindows package and what is the contents of the `chocolateyInstall.ps1` file inside of it?

**Comment by pauby** [comment]
Closing this as stale.
