### ISSUE TITLE
Add multiple monitor support to Set-TaskbarOptions

### ISSUE THREAD

**Issue by HolisticDeveloper** [chocolatey/boxstarter#399]
This request is to enable support for the "Multiple displays" settings found in Windows 10:

- Show taskbar on all displays
- Show taskbar buttons on
  - All taskbars
  - Main taskbar and taskbar where window is open
  - Taskbar where window is open
- Combine buttons on other taskbars
  - Always, hide labels
  - When taskbar is full
  - Never

These are set with the following registry values under HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced (thanks to https://finnzan.blogspot.com/2017/01/windows-10-taskbar-customization.html):

MMTaskbarEnabled
0 = Don't show taskbar on multiple displays
1 = Show taskbar on multiple displays

MMTaskbarMode DWORD
0 = Show taskbar buttons on all taskbars
1 = Show taskbar buttons on main taskbar and taskbar where window is open
2 = Show taskbar buttons on taskbar where window is open

MMTaskbarGlomLevel
0 = Always combine, hide labels
1 = Combine when taskbar is full
2 = Never combine

This seems pretty straightforward so I'm happy to contribute a PR for this.

**Comment by flcdrg** [comment]
Sounds good!

**Comment by HolisticDeveloper** [comment]
PR has been submitted (#400).

**Comment by veleek** [comment]
@pauby - This was closed in February, and the documentation refers to the new function, but I just installed BoxStarter moments ago and it's still got the old function.  Am I doing something wrong?  Does the new function need to be exported somewhere?

**Comment by veleek** [comment]
@pauby - Okay, just figured this out.  The bootstrapper.ps1 script has been updated to 2.13.0, in the repo, but the one pointed to by the installation instructions (https://boxstarter.org/bootstrapper.ps1) is still the old version.

**Comment by veleek** [comment]
Issue #458 opened to resolve some additional problems with this new implementation.
