### ISSUE TITLE
Improper Parsing of Chocolatey Parameter

### ISSUE THREAD

**Issue by Heteroculturalism** [chocolatey/boxstarter#405]
### What You Are Seeing?
Failure to parse Chocolatey parameter

### What is Expected?
Correctly parsing Chocolatey parameter

### How Did You Get This To Happen? (Steps to Reproduce)
boxstarter script.ps1

where script.ps1 only contains

`choco install -y cmake --installargs "ADD_CMAKE_TO_PATH=System"`

However, 
`choco install -y cmake --installargs="ADD_CMAKE_TO_PATH=System"` works fine, which makes me think it's simply a parsing issue.

### Output Log

<details>
<summary>Full Log Output</summary>

<p>

~~~sh
Boxstarter starting Calling Chocolatey to install --installargs. This may take several minutes to complete...
Boxstarter starting Calling Chocolatey to install --installargs. This may take several minutes to complete...
Installing the following packages:
cmake;ADD_CMAKE_TO_PATH=System
By installing you accept licenses for the packages.
cmake v3.15.2 already installed.
Use --force to reinstall, specify a version to install, or try upgrade.
ADD_CMAKE_TO_PATH=System not installed. The package was not found with the source(s) listed.
If you specified a particular version and are receiving this message, it is possible that the package name exists but the version does not.
Version: ""
Source(s): "https://chocolatey.org/api/v2/"
~~~

</p>

</details>

**Comment by mwallner** [comment]
this is somehow related to #265 - Boxstarter definitely needs some work on it's command parsing, as it simply tries to install an array of packages after a `choco install` command.

note, this should only applies to "Boxstarter packages", not when using BoxstarterShell.

**Comment by mwallner** [comment]
note that #404 does _NOT_ resolve this bug.

**Comment by pauby** [comment]
@mwallner You happy to take this one on?

**Comment by mwallner** [comment]
In _theory_ `Call-Chocolatey` already handles arbitrary arguments passed to chocolatey.

```
function Call-Chocolatey {
    param(
        [string]$command,
        [string[]]$packageNames=@('')
    )
    $chocoArgs = @($command, $packageNames)
    $chocoArgs += Format-ExeArgs $command @args
    Write-BoxstarterMessage "Passing the following args to Chocolatey: $chocoArgs" -Verbose
```

.. relates to #145

**Comment by mwallner** [comment]
Oh, the code in https://github.com/chocolatey/boxstarter/blob/master/Boxstarter.Chocolatey/Chocolatey.ps1#L301 only checks for `=` separated parameters, imo this is the correct place for fixing this.

**Comment by mwallner** [comment]
I've just written a couple of tests and verified: there definitely is a bug in choco command parsing that leads to argument reordering before those args are passed to choco.exe.

i.e.:
```
choco Install -y pkg --source blah --installargs "ADD_CMAKE_TO_PATH=System"
```

I've added a couple of Debug-print statements to `function chocolatey`:
```
Write-BoxstarterMessage "chocolatey wrapper: PSBoundParameters: '$($PSBoundParameters.Keys | % { "`r`n  $($_) -> $($PSBoundParameters[$_])" })`r`n'" -Verbose
Write-BoxstarterMessage "chocolatey wrapper: args: $($args | % { $_ })" -Verbose
```

which gives me
```
VERBOSE: Boxstarter: chocolatey wrapper: PSBoundParameters: '
  command -> Install
  packageNames -> --source
'
VERBOSE: Boxstarter: chocolatey wrapper: args: -y pkg blah --installargs ADD_CMAKE_TO_PATH=System
```

that finally leads to 
```
Install --source -y pkg blah --installargs ADD_CMAKE_TO_PATH=System
```
being passed to choco.exe.
(which is bad, as '--source blah' needs to be kept in correct order, also the quotes of the '--installargs'  parameter are lost).

After all, `function cinst`, `function choco`, `function cup` as well as `function chocolatey` need to be fixed to keep the original parameter order.

**Comment by pauby** [comment]
Build is failing in AppVeyor. Once that is resolved we can get to merging this.

Awesome work @mwallner. Thanks for picking this up and completing it!
