### ISSUE TITLE
Unable to resolve dependency during install

### ISSUE THREAD

**Issue by mlafleur** [chocolatey/boxstarter#414]
While attempting to install Boxstarter, I receive the following error:

``` 
Boxstarter not installed. An error occurred during installation:
 Unable to resolve dependency 'Boxstarter.Common (= 2.12.0)'.
```
This exception is triggered using both `setup.bat` and `cinst boxstarter` methods. 
I am able to install `cinst boxstarter.common` and get past the above error but it just stops at the next component:

```
boxstarter not installed. An error occurred during installation:
 Unable to resolve dependency 'Boxstarter.WinConfig (= 2.12.0)'.
```

**Comment by gep13** [comment]
@mlafleur this is related to a recent change to chocolatey.org. We have an issue here where we are tracking this...

https://github.com/chocolatey/chocolatey.org/issues/765

As such, I am going to close this issue.
