### ISSUE TITLE
boxstarter.org has an outdated copyright notice

### ISSUE THREAD

**Issue by notriddle** [chocolatey/boxstarter#415]
### What You Are Seeing?

At the bottom of boxstarter.org, it says it's (c) 2018 Chocolatey Software Inc.

### What is Expected?

(c) 2018-2019 Chocolatey Software Inc.

### How Did You Get This To Happen? (Steps to Reproduce)

Visit https://boxstarter.org and scroll down.

**Comment by ferventcoder** [comment]
There we go. @pauby you may have another issue with this same, so triage please. :D

**Comment by Miles-Davies-HORIBA** [comment]
This is a style and not an issue maybe? The issue with a closing copyright date is every year you have at least one date to change. In theory the copyright begins when the document/source/software is first published and expires after a set number of years (depending on local laws - could be as many as 60 years)
Putting a second date is not correct nor required
