### ISSUE TITLE
webstarter `/package/nr/` no longer works. In stead of noreboot, an install of "nr" is attempted.

### ISSUE THREAD

**Issue by Redsandro** [chocolatey/boxstarter#430]
### What You Are Seeing?

Launching ClickOnce url `https://boxstarter.org/package/nr/?package=app1,app2,app3` causes

1. `nr` to be installed as a package, which always fails.   
`/package/nr/` used to be the route to toggle `-noreboot`.
2. `-noreboot` flag is not set

### What Is Expected?

- Install `app1`, `app2` and `app3`
- Do not reboot
- **Do not try to install a package called `nr`**

### How Did You Get This To Happen? (Steps to Reproduce)

Use any old script you used to use for provisioning.

For example, open admin terminal and enter the following:

```cmd
START https://boxstarter.org/package/nr/?package=unchecky
```

### Output

```cmd
Boxstarter: Installing package nr, unchecky
Boxstarter Version 2.12.0
(c) 2018 Chocolatey Software, Inc, 2012 - 2018 Matt Wrock. https://boxstarter.org

Please type CTRL+C or close this window to exit Boxstarter if you do not want to risk a reboot during this Boxstarter install.

Boxstarter may need to reboot your system.
Please provide your password so that Boxstarter may automatically log you on.
Your password will be securely stored and encrypted.
Autologon Password:
```

### Relevant Code

https://github.com/chocolatey/boxstarter/blob/5880cb112afa5bfeab39f1bd8b761681fe90e7c3/Web/Web.config#L26-L33

**Comment by flcdrg** [comment]
Do you get the same problem if you use the syntax described on https://boxstarter.org/WebLauncher ?

eg.

```
https://boxstarter.org/package/nr/app1,app2,app3
```

**Comment by Redsandro** [comment]
@flcdrg you are correct. I believe the (very) old syntax is conflicting with the new(er) syntax, because the query parameter works, but `nr` is added as a package.

There are two functioning ways to install packages without causing a reboot.

**1.** :heavy_check_mark: Newest method, **works**:

```
https://boxstarter.org/package/nr/app1,app2,app3
```

**2.** :heavy_check_mark: query param for `noreboot`, **works**:

```
https://boxstarter.org/package/app1,app2,app3?noreboot=1
```

**3.** :warning: Old query method, **working but** `nr` is erroneously added to the package list in stead of triggering the `-noreboot` flag:

```
https://boxstarter.org/package/nr/?package=app1,app2,app3
```

**4.** :no_entry_sign: Old full query method **not working**:

```
https://boxstarter.org/package/?package=app1,app2,app3&noreboot=1
```

---

While it is easy to fix an old script, it would be less confusing if it either works (correctly) or doesn't work (at all).

It might be a good idea to either fix the `nr` route when using the `package` query parameter (for backwards compatibility), or  remove the `package` query parameter altogether (to prevent this mixed old/new syntax conflict).

**Comment by pauby** [comment]
Looking at this, there isn't anything to do here. The suggestion is to amend the ClickOnce installer, which we don't plan to do. I feel the documentation is clear on how it should be used.

I'm going to go ahead and close it. We can always reopen it again if needed.
