### ISSUE TITLE
Install Windows Updates offline

### ISSUE THREAD

**Issue by bilalinamdar** [chocolatey/boxstarter#437]
Dear Team,

I work on server deployments and we have certain templates of windows 2012 r2, 2016, 2019 which need updating after deployment for which i am trying to using Boxstarter and Chocolatey combo.

Boxstarter works Properly for Windows Update but i want to do Windows Update offline to save on bandwwidth and time.

How can i achieve that with Boxstarter ? Looking forward for a solution !

Regards,
Bilal Inamdar

**Comment by pauby** [comment]
There are three ways to do this (in order of _my_ preference):

*  Create an internal WSUS server and use the `Install-WindowsUpdate` function. That function has the [GetUpdatesFromMS switch](https://github.com/chocolatey/boxstarter/blob/master/Boxstarter.WinConfig/Install-WindowsUpdate.ps1#L9-L10) that will override any update servers set and download directly from Microsoft. If you don't set that, and the server is configured to use your internal WSUS server, then it should download from there instead;
* You could download the updates you need beforehand, create a Chocolatey package for them, and install them using the normal `choco install` command;
* You could download the updates you need beforehand and install them normally (using silent switches);

Note that this isn't really a Boxstarter issue.

**Comment by mkevenaar** [comment]
Another option would be, if you don't want to configure a WSUS server, is to install [WSUS Offline](https://chocolatey.org/packages/wsus-offline-update) on a central server, download the updates and install it using their scripts. 
**NOTE**: I don't know how "nice" it plays with BoxStarter.

**Comment by bilalinamdar** [comment]
Hi Guys,
Thanks for all the input I will do as suggested !
