### ISSUE TITLE
Please read VU#208577 from CERT

### ISSUE THREAD

**Issue by wdormann** [chocolatey/boxstarter#440]
### What You Are Seeing?

Vulnerability VU#208577 was reported to security@chocolatey.io several days ago, but the case hasn't yet been viewed.

### What Is Expected?

Somebody at Chocolatey viewed the report.

### How Did You Get This To Happen? (Steps to Reproduce)

Notified security@chocolatey.io about a vulnerability.

### Output Log

N/A

**Comment by pauby** [comment]
As mentioned when raising an issue:

Please do not raise Security issue in this repository. Use the link to report them responsibly. Thank you. 

Closing this issue.
