### ISSUE TITLE
Add functionality to set-windowsexploreroptions.ps1 to allow for enabling and disabling of check boxes next to items.

### ISSUE THREAD

**Issue by demdante** [chocolatey/boxstarter#443]
Big fan of boxstarter.  Use it a lot.  One enhancement I would like to see added is the ability to configure windows explorer to enable or disable check boxes next to items in Windows Explorer.  These check boxes in Windows Explorer allow for users to select/deselect objects in windows explorer by checking/unchecking the check box next to the file/folder.  Think of it as an alternative to holding down the "ctrl" button and selecting multiple items:

![go](https://user-images.githubusercontent.com/64720591/97384456-a45c4100-18c7-11eb-86f2-9dacc5b030ba.gif)

 As of now, boxstarter does not have this functionality.

**Is your feature request related to a problem? Please describe.**
No.  not related to a problem.  Simply an enhancement. 

**Describe the solution you'd like**
I already implemented it.  This is simply a formality, as the contributing page indicated a feature request was needed for pull requests.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by pauby** [comment]
@demdante Thanks for the issue. Without any context around this I don't know what this enhancement is. The text 'enabling and disabling of check boxes next to items' doesn't give me enough information. Can you please provide additional information above and some screenshots to help us understand?
