### ISSUE TITLE
Deprecate Testrunner and Hyper-V Modules

### ISSUE THREAD

**Issue by pauby** [chocolatey/boxstarter#453]
**Describe the solution you'd like**
The Hyper-V and Testrunner modules don't appear to be used much at all. So we should look at deprecating them in a future version.

**Comment by alias86** [comment]
What do you guys test with?

About 6 weeks into choco and trying to come up with a basic test frame work

**Comment by kirannhegde** [comment]
Hello, @pauby I don't think these modules have to be deprecated.  I just started using them and deprecating something which works flawlessly would be not in the larger interest of the Boxstarter community. Unless there is a reliable alternative which can work both Onprem as well as in the cloud, we should continue to keep these modules.

I maintain about 150 chocolatey packages, i am currently updating these packages to be automatic and the ability to test these packages and make them as part of a CI pipeline is extremely important to me.

If there is a strong reason for deprecating these modules, please provide an alternative to these modules. I would like something which scales the underlying infrastructure depending upon the number of choco packages waiting in the queue to be tested as well.

@alias86 If you have come with an alternative mechanism, please let me know. I have explored a few and I did be happy to share them with you as well.

Thanks,
Kiran Hegde

**Comment by pauby** [comment]
@kirannhegde Thanks for that.

As I said in the original message, the reason we were looking at deprecating them (and this has been a long running thought) is that the modules were not being used and therefore the cost of supporting them wasn't worth it.

However, given your comments perhaps we need to rethink that.

**Comment by alias86** [comment]
@kirannhegde 

Hey, thanks for your reply to the thread.

I'm just getting started with Boxstarter, this week.
Just working with a basic script and a HyperV box.

I would be very grateful if you could share some details around your set.

Feel free to PM me

**Comment by kirannhegde** [comment]
Hello, @alias86 I am back to my old project of testing Chocolatey packages. Were you able to put together a test framework for testing Choco packages? I am currently also using the Chocolatey Auto updater module to update my Choco packages. So ideally, I would like the testing to be integrated with the Chocolatey auto-update module.

**Comment by pauby** [comment]
We're getting off-topic on this. The purpose of this thread is to discuss deprecating the Hyper-V and Testrunner modules. As it looks like these are still used then I think we should keep them as part of Boxstarter. However, we may not be able to provide as much support around these.
