### ISSUE TITLE
bootstrapper.ps1 still reflects 2.12.0 version

### ISSUE THREAD

**Issue by bruckect** [chocolatey/boxstarter#459]
### What You Are Seeing?

Depending on the CDN that I am connected to, it seems that bootstrapper.ps1 is sometimes referencing version 2.12.0 and other times referencing 2.13.0. I have connected from my home connection (Spectrum) and get 2.12.0. When I connect with a hotspot (Verizon) or an alternate ISP, I get 2.13.0.

### What Is Expected?

I expect that I always get the latest version 2.13.0 (at time of writing).

### How Did You Get This To Happen? (Steps to Reproduce)

My home connection is Spectrum based out of Cincinnati, OH.
![image](https://user-images.githubusercontent.com/11944255/102268673-98fdbd00-3ee9-11eb-8960-e6dd1dd7754e.png)

**Comment by pauby** [comment]
@bruckect It turns out this wasn't a CDN issue but the `bootstrapper.ps1` script not being updated upon release. I'm not sure why not.

I have updated it now and can see it being reported when you go to https://boxstarter.org/bootstrapper.ps1. Can you check this?

**Comment by bruckect** [comment]
It is showing updated now. Very strange that it was showing updated at one point based on different connections.

**Comment by pauby** [comment]
Yeah, that is very strange. I'll go ahead and close this one off.

Thanks for reporting it!
