### ISSUE TITLE
LoadFromRemoteSources exception running an Install from a network share or external media

### ISSUE THREAD

**Issue by Jaykul** [chocolatey/boxstarter#461]
### What You Are Seeing?

When I try to run boxstarter 2.13 from a network share, like:

```PowerShell
\\server\BoxStarter\BoxStarter example -DisableReboot -Debug -Verbose
```

It cannot load log4net because "An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework."

I get an error like:

```Console
Boxstarter: Error from Chocolatey:

Message        : Could not load file or assembly
                 'file://\\server\BoxStarter/boxstarter.chocolatey/chocolatey/log4net.dll' or one of its
                 dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
FileName       : file://\\server\BoxStarter/boxstarter.chocolatey/chocolatey/log4net.dll
FusionLog      :
Data           : {}
InnerException : System.NotSupportedException: An attempt was made to load an assembly from a network location which
                 would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This
                 release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous.
                 If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch.
                 See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
````

### What Is Expected?

It should install the package ...

### How Did You Get This To Happen? (Steps to Reproduce)

I followed the steps in the [Running an Install from a network share or external media](https://boxstarter.org/InstallingPackages#InstallFromShare) section.

1. Copy BoxStarter folder to UNC path
2. Run Boxstarter.bat from UNC path (fails)

I also tried mapping a drive letter, in case that mattered. I'm pretty sure it would need a PowerShell.exe.config file to fix it, per [http://go.microsoft.com/fwlink/?LinkId=155569](http://go.microsoft.com/fwlink/?LinkId=155569), but in the meantime, this happens **every** time.

### Output Log

I think all you _really need_ is what I posted above, but I posted the [full -debug -verbose log](https://gist.github.com/Jaykul/7756744fcfb308607c13df5ba76dba79) from the run with a drive letter.

**Comment by mwallner** [comment]
I think this is the same issue as in #327 - we sbould investigate if we can default to
```
    [System.Reflection.Assembly]::Load([io.file]::ReadAllBytes($_))
```
instead of using 
```
    Add-Type -Path $_
```
as per [comment of SheGe](https://github.com/chocolatey/boxstarter/issues/327#issuecomment-409476855)

**Comment by Jaykul** [comment]
I agree. I couldn't find that issue, but this is clearly the same.
For what it's worth, adding this to `BoxStarter.bat` worked (although it feels slower now):

```cmd
set TestingBoxstarter=True
```
