### ISSUE TITLE
Support for Windows 10 and future Windows 11

### ISSUE THREAD

**Issue by kiquenet** [chocolatey/boxstarter#470]
**Is your feature request related to a problem? Please describe.**
Support for Windows 10 

**Describe the solution you'd like**
Support for Windows 10  and Azure

**Describe alternatives you've considered**
none

**Additional context**
powershell chocolatey for HyperV in Windows 10 and 11 and Azure

**Comment by flcdrg** [comment]
Boxstarter already works with Windows 10. Can you be a bit more specific about what functionality you think is missing?

**Comment by flcdrg** [comment]
Closing due to lack of response. Please add a comment if you have any more info to add
