### ISSUE TITLE
Autologon supports Windows Hello PIN

### ISSUE THREAD

**Issue by soricinae** [chocolatey/boxstarter#475]
Today: when I run http://boxstarter.org/package/url?xxxxxx, boxstarter asks for my password (prompt: `Autologon password: `). If I give my Windows Hello PIN, then autologon does not accept it (it tries 3x then says: `Boxstarter: Unable to authenticate password for computerName\accountName. Proceeding with autologon disabled`).

Ideally: boxstarter supports autologon for Windows Hello PIN so restarts can continue without user intervention.

**Comment by vexx32** [comment]
I was under the impression that automatic login is effectively not possible if you have a Windows Hello authentication method enabled 🤔 

I'm unsure if there's a way for tooling to work around that... [This article](https://www.intowindows.com/how-to-automatically-login-in-windows-10/) mentions it briefly, but I've not been able to find much definitive information on any way an automated tool could work with Windows Hello:

> **IMPORTANT:** Auto or automatic login might not work if Windows Hello PIN and Windows Hello Fingerprint or any one of these are enabled. Navigate to Settings > Accounts > Sign-in options page and then remove these two sign-in options.

**Comment by pauby** [comment]
This isn't something we have on the roadmap because of the way the autologon works (part of which @vexx32 pointed out above). At the moment it's a username and password that's required.

**Comment by flcdrg** [comment]
Just to confirm - I've just used Boxstarter on a new machine that has Windows Hello-capable hardware. For Boxstarter I used the account name and password. I am not aware of any alternative to using a password (short of you sitting in front of your machine smiling at your Windows Hello camera or with your finger on the fingerprint reader 😃 )
