### ISSUE TITLE
Controlling the install order of multiple boxstarter packages specified on command line

### ISSUE THREAD

**Issue by DarwinCSIWindowscom** [chocolatey/boxstarter#48]
I was hoping that boxstarter would process the packages I handed it in the order I put them in the array - but it does not seem to be using the order passsed, reverse order or alpha sorted order.  I am creating an array and passing it on the command line if that makes any difference to the outcome.

I googled the daylights out of it and couldn't find an answer - so Is there a way to control the order of a list of packages I give it?

If the order cannot be guaranteed, would it be possible to sort the array so that I could at least control order by file naming?

I am also considering manually concatenating the individual box starter scripts and call it as one new script - but it seems like I shouldn't have to do that to support stipulated package ordering.
D.

**Comment by DarwinCSIWindowscom** [comment]
OK - these are actually dynamically generated boxstarter scripts - so I had to manually concenate them anyway because doing them on the boxstarter command line results in trying to install the same named package multiple times.

**Comment by mwrock** [comment]
Yeah. Boxstarter does not do any reordering and processes everything top to bottom. I'm assuming the script generation you are referring to is happening on your end?

**Comment by DarwinCSIWindowscom** [comment]
Yes - I have a calling script that concatenates them.  Have also worked out a way to reliably have a *local* include script with my own functions for prompting,etc.

It would sure be nice if when boxstarter receives a list of scripts that aren't npkg files that it would create "temp1", "temp2", "temp3" and then chain them together so that the multiple package support was built in for temporary packages as well :)

**Comment by mwrock** [comment]
Hmm. I'm not sure I'm following you. Can you clarify "giving boxstarter a list of scripts?" Maybe provide an example of how you are calling it?

Thanks!

**Comment by DarwinCSIWindowscom** [comment]
So if I do:

Install-BoxstarterPackage @(package1, package2) 

Where package1 and package 2 are script files that boxstarter dyamically compiles into the temp package.  It seems to compile each script into the same named temp package - every additional one after the first one says that the package is already installed.

**Comment by mwrock** [comment]
ahhh. gotcha. Unfortunately Boxstarter handles script files differently than true packages which is not documented and clearly suboptimal. You can work around this however by doing something like this:

```
@(package1, package2) | % { Install-BoxstarterPackage $_ }
```

**Comment by DarwinCSIWindowscom** [comment]
I don't think that would persist through a reboot right?  Because if script 2 of 5 reboots it wouldn't restart my script that is doing the above loop?

So I am doing this:

@("$PSScriptRoot\script1.txt", "$PSScriptRoot\script2.txt", "$PSScriptRoot\script3.txt") | %{Get-Content $_ | Add-Content "consolidatedscript.txt"}

Install-BoxstarterPackage -PackageName consolidatedscript.txt

**Comment by mwrock** [comment]
You are correct assuming you are calling it locally.

Sent from my Windows Phone
________________________________
