### ISSUE TITLE
Installation of remote package does not start with 2.13.16 artifacts

### ISSUE THREAD

**Issue by Baune8D** [chocolatey/boxstarter#481]
### What You Are Seeing?

Boxstarter never initiates remote install and just hangs on `Boxstarter starting Calling Chocolatey to install MagicScript. This may take several minutes to complete...`

![image](https://user-images.githubusercontent.com/30204280/139649761-e11d5b5a-578b-4c20-9ac2-b42855f651e0.png)

I can verify that remoting works, because i can see Boxstarter trigging scripts on the remote machine on setup and teardown.

### What Is Expected?

Remote install is expected to start.

### How Did You Get This To Happen? (Steps to Reproduce)

This issue only happens with the 2.13.16 artifacts from AppVeyor https://ci.appveyor.com/project/chocolatey/boxstarter/builds/41341291/artifacts

Using Boxstarter 2.13.0 the remote installations starts correctly.

Remote install is kicked off from the host with `Install-BoxstarterPackage -ComputerName $hostname -PackageName $package -Credential $cred -StopOnPackageFailure` against a Hyper-V VM (Generation 2, Configuration 10).

Host is using Chocolatey 0.11.3

**Comment by mwallner** [comment]
Hi @Baune8D , 
1. you are awesome, thanks for catching this. 
2. just to be clear: the AppVeyor PR-build artifacts are not meant to be used in production, we'll add a `-beta` suffix asap so people will not accidentally roll out these "valid-looking" build versions.
3. of course I want people to grab the latest artifacts and play around with them / discovering bugs as early as possible.
4. see 1.

**Comment by Baune8D** [comment]
Yes i get that 😄 I just want to help get this out, since i currently have to do a lot of workarounds for the old chodolatey.dll

**Comment by pauby** [comment]
Same issue I mentioned previously. We appreciate the help on this @Baune8D, but as this is not an official build can any problems be added to the PR?

**Comment by Baune8D** [comment]
> Same issue I mentioned previously. We appreciate the help on this @Baune8D, but as this is not an official build can any problems be added to the PR?

I understand. Both issues has been moved to https://github.com/chocolatey/boxstarter/pull/479
