### ISSUE TITLE
Installation of chocolatey package triggers verbose information and ends in a loop using 2.13.16 artifacts

### ISSUE THREAD

**Issue by Baune8D** [chocolatey/boxstarter#482]
### What You Are Seeing?

When installing chocolatey package through Boxstarter 2.13.16, it triggers alot of verbose information and ulimately ends in a loop with the message `Checking for other running MSIEXEC installers...`

### What Is Expected?

Chocolatey package should install correctly and without verbose information.

### How Did You Get This To Happen? (Steps to Reproduce)

Calling `choco install 'git' --no-progress` in a Boxstarter package.

This issue only happens with the 2.13.16 artifacts from AppVeyor https://ci.appveyor.com/project/chocolatey/boxstarter/builds/41341291/artifacts

Using Boxstarter 2.13.0 the installation runs correctly.

### Output Log

Log from `%LOCALAPPDATA%\Boxstarter\boxstarter.log`
https://gist.github.com/Baune8D/f5618641b173d5c150dc33e94ba77526

**Comment by Baune8D** [comment]
@mwallner just tagging you here since this relates to the `2.13.16` artifacts

**Comment by pauby** [comment]
Version 2.13.16 is not an official release of Boxstarter. Can you provide feedback on the PR that created the artifacts?
