### ISSUE TITLE
Reboot loop in Windows 11

### ISSUE THREAD

**Issue by stevehurcombe** [chocolatey/boxstarter#490]
### What You Are Seeing?
This is a clean install of Windows 11 on a Dell laptop. 

I've just installed choco and boxstarter and I want to use boxstarter to configure my dev machine.

I'm using a simple script, thus:

`choco install -y Boxstarter`

Then I would run:

`Install-BoxstarterPackage -PackageName install.ps1`

This causes a reboot loop.

### What Is Expected?

install my applications using the powershell script, with reboots if needed.

### How Did You Get This To Happen? (Steps to Reproduce)

```
choco install -y Boxstarter

Install-BoxstarterPackage -PackageName install.ps1
```

Where install.ps1 contains:

`Get-Command -Module Microsoft.PowerShell.Archive`

### Output Log
![image](https://user-images.githubusercontent.com/2033186/152511025-3c228065-0a23-4191-8d2e-61093a2136b1.png)

**Comment by flcdrg** [comment]
I seem to have reproduced this today. Clean install of Windows 10, upgraded to Windows 11. Then ran 

```
Install-BoxstarterPackage -PackageName https://gist.githubusercontent.com/flcdrg/87802af4c92527eb8a30/raw/11b1179afd7145c4b17d55d342af6ae8e2ce7b8a/boxstarter-bare-v3.ps1 -Credential $cred
```

Attached boxstarter log
[boxstarter.log](https://github.com/chocolatey/boxstarter/files/10333731/boxstarter.log)

**Comment by flcdrg** [comment]
I think this might be because I have some files that are supposedly pending a rename, but multiple reboots isn't clearing them.

```
Computer           : DELPHINE
CBServicing        : False
WindowsUpdate      : False
CCMClientSDK       :
PendComputerRename : False
PendFileRename     : True
PendFileRenVal     : {\??\C:\Program Files\Waves\IntelOpenVINO1\plugins.xml_, , \??\C:\Program
                     Files\Waves\IntelOpenVINO1_, ...}
RebootPending      : True
```

**Comment by flcdrg** [comment]
This is caused by the Intel audio driver incorrectly marking that a reboot is needed. Latest drivers should have resolved the problem.

See https://www.reddit.com/r/sysadmin/comments/10fas8x/intel_openvino_causing_daily_reboots_related_to/?rdt=54860 for more info

**Comment by stevehurcombe** [comment]
Thank you for that.
I don't suppose there's any way to adjust the logging to surface the cause? This will help if something else does the same thing.

**Comment by flcdrg** [comment]
Interesting suggestion. I'll create a separate issue for that
