### ISSUE TITLE
Breaking changes from Chocolatey 1.0.0

### ISSUE THREAD

**Issue by OraDotNetDev** [chocolatey/boxstarter#496]
There are a few references to helper functions which have been removed in  Chocolatey 1.0.0  https://github.com/chocolatey/choco/issues/2469. 

Do these now need to be removed (and replaced)?

https://github.com/chocolatey/boxstarter/blob/a0e83108c20a8926303830cb2d5b96d6256f3765/Boxstarter.Chocolatey/Get-PackageRoot.ps1#L31

https://github.com/chocolatey/boxstarter/blob/a0e83108c20a8926303830cb2d5b96d6256f3765/Boxstarter.Chocolatey/Get-PackageRoot.ps1#L33

https://github.com/chocolatey/boxstarter/blob/a0e83108c20a8926303830cb2d5b96d6256f3765/Boxstarter.Chocolatey/New-BoxstarterPackage.ps1#L100

https://github.com/chocolatey/boxstarter/blob/a0e83108c20a8926303830cb2d5b96d6256f3765/Boxstarter.Chocolatey/New-BoxstarterPackage.ps1#L102

**Comment by pauby** [comment]
For backwards compatibility the Chocolatey Community will be adding those functions into an extension module (likely `chocolatey-core.extension`) in the short term. Longer term we will need to remove this functions from the Boxstarter code.

Thanks for picking that up @OraDotNetDev

**Comment by gep13** [comment]
While updating this, it might be advisable to remove any usage of the now deprecated Chocolatey shims, or example `cinst`, `clist`, etc.

**Comment by OraDotNetDev** [comment]
> While updating this, it might be advisable to remove any usage of the now deprecated Chocolatey shims, or example `cinst`, `clist`, etc.

Not very familiar with Boxstarter, but looks as though it has **it's own** [wrapper functions](https://github.com/chocolatey/boxstarter/blob/a0e83108c20a8926303830cb2d5b96d6256f3765/Boxstarter.Chocolatey/Chocolatey.ps1#L89) for cup, cinst to override the now removed chocolatey aliases.

Could it just be case of renaming these to avoid any confusion?

**Comment by mwallner** [comment]
Hi @OraDotNetDev - thanks for bringing this up, we'll definitely need to do something about the `Write-Chocolatey...` functions being deprecated. (I'll take care of it asap, but won't be in the upcoming 'v3' release)

As for `cinst / cup / ...` there's really nothing to be done there - these shims are monkey patched by the wrapper functions you discovered.

**Comment by pauby** [comment]
A [`chocolatey compatibility`](https://community.chocolatey.org/packages/chocolatey-compatibility.extension) extension has been created that might help with this.

**Comment by mwallner** [comment]
I'm going to close this issue as it is going to be implicitly fixed with Boxstarter v3 / GH-479
