### ISSUE TITLE
Update iconUrl to a domain owned directly have Chocolatey

### ISSUE THREAD

**Issue by gep13** [chocolatey/boxstarter#508]
## Is Your Feature Request Related To A Problem? Please describe.

Currently, the iconUrl for the Boxstarter Chocolatey packages uses:

```
https://cdn.rawgit.com/chocolatey/boxstarter/master/Web/Images/boxLogo_sm.png
```

During the recent v3.0.0 release, this URL failed to validate, since the entire Web directory was removed from the Boxstarter GitHub repository.  To prevent this from happening again, the iconUrl should be updated to a URL that is directory owned/maintained by Chocolatey.

## Describe The Solution. Why is it needed?

Suggestion would be to add the Boxstarter logo to this [repository](https://github.com/chocolatey/img) and the iconUrl would be updated to start with https://img.chocolatey.org

The old image likely needs to remain in the GitHub Repository, so that the icon for older package versions continues to work.

## Additional Context.

N/A

## Related Issues

N/A

**Comment by pauby** [comment]
@st3phhays I'm happy to pick this up and put the image into img.chocolatey.org. However, where do you want it to go (folder) and what do you want it called (filename)? Not sure if you have a format for that over there.

**Comment by st3phhays** [comment]
@pauby Thanks!

Copy these two images:
* https://github.com/chocolatey/boxstarter.org/blob/master/input/assets/images/boxstarter-logo-sm.png
* https://github.com/chocolatey/boxstarter.org/blob/master/input/assets/images/boxstarter-logo.png

Place them into a folder on the images repo under `logos/` (so it'll be `img.chocolatey.org/logos/boxstarter-logo.png` for example)

I'll put the rest of the Chocolatey logos in this folder as well once those are moved over.

**Comment by pauby** [comment]
Raised a PR to have the images added. Once that is merged we can complete this.
