### ISSUE TITLE
Install Boxstarter from URL fails on Windows 8.1: Cannot process argument because the value of argument "type" is not valid

### ISSUE THREAD

**Issue by kurone-kito** [chocolatey/boxstarter#513]
### What You Are Seeing?

Boxstarter installation from URL fails on Windows 8.1.

<https://boxstarter.org/package/boxstarter>

Setup creates a shortcut to the desktop for the Boxstarter Shell while logging a failure but then fails to install from a custom scripted URL. Hence, it appears that it is probably partially installed incorrectly.

P.S: The reason for installing Boxstarter by itself from a URL is that if I install a custom script from a URL prior to that, it will succeed but not execute anything.

### What is Expected?

Installation succeeds without producing red error logs.

### How Did You Get This To Happen? (Steps to Reproduce)

The problem can be reproduced on Windows 8.1 by installing Boxstarter from the URL below.

<https://boxstarter.org/package/boxstarter>

I have also prepared a repository to reproduce the problem using Vagrant and Virtualbox, for those who do not have a Windows 8.1 environment.

<https://github.com/kurone-kito/boxstarter-probrem-reproduction-for-win81>

### System Details

* OS Build (In PowerShell run `[System.Environment]::OSVersion.version.tostring()`): `6.3.9600.0`
* Windows PowerShell version (Run: `$PSVersionTable`):

```txt
Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.34014
BuildVersion                   6.3.9600.16394
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
```

* Chocolatey version (Run `choco --version`): _(Not installed)_

### Output Log

See:

* <https://github.com/kurone-kito/boxstarter-probrem-reproduction-for-win81/blob/main/chocolatey.log>
* <https://github.com/kurone-kito/boxstarter-probrem-reproduction-for-win81/blob/main/choco.summary.log>

**Comment by pauby** [comment]
As [Windows 8.1 is no longer a supported operating system](https://learn.microsoft.com/en-us/lifecycle/products/windows-81) (but was when this was raised), I'm going to go ahead and close this. We can reopen it if necessary.
