### ISSUE TITLE
bootstrapper is failing with Chocolatey v2

### ISSUE THREAD

**Issue by flcdrg** [chocolatey/boxstarter#532]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

https://twitter.com/Cyberipman/status/1665420846234574848

### What is Expected?

Works with Chocolatey v2.0

### How Did You Get This To Happen?

Using bootstrapper script

### System Details

* Chocolatey CLI Version: 2.0

### Installed Packages

```bash
n/a
```

### Output Log

```bash
n/a
```

**Comment by Ana06** [comment]
Until #533 is merged and released, you can use `$env:chocolateyVersion = '1.4.0'` before installing boxstarter
