### ISSUE TITLE
Boxstarter (weblauncher) always installs latest version of Chocolatey

### ISSUE THREAD

**Issue by mwallner** [chocolatey/boxstarter#537]
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my problem.
- [X] I have verified this is not an issue for a specific package.
- [X] I have verified this issue is not security related.

### What You Are Seeing?

Chocolatey 1.1 is installed (packaged with Boxstarter), then Boxstarter immediately installs the latest available Chocolatey version.

![image](https://github.com/chocolatey/boxstarter/assets/5354972/c0424a08-b2e2-4298-a320-34732510f7a4)

With version 3.0.1, - caused by GH-534, Boxstarter will try to install the latest version of Chocolatey, even if the builtin/pre-packaged version of Chocolatey is installed first.

 

### What is Expected?

Boxstarter should stick to the bundled version of Chocolatey (as it's the one that's tested and verified to work with Boxstarter), as long as the user has not manually upgraded to a newer version of Chocolatey. 

### How Did You Get This To Happen?

START https://boxstarter.org/package/nr/url?https://gist.githubusercontent.com/mwallner/a339c90c45978ca19e243a52b12ea3f8/raw/693e7b246b35ca967c1554e91fe5afbcf6f52dce/min-pwsh-win-boxstarter.ps1

### System Details

* Operating System: Win11 (StefanScherer Vagrant Box)

### Installed Packages

```bash
-
```

### Output Log

```bash
see screenshot above.
```

**Comment by mwallner** [comment]
verified that it works as intended if a (supported) version of Chocolatey is already installed when Boxstarter Weblauncher is being used: 
![image](https://github.com/chocolatey/boxstarter/assets/5354972/7ae37615-aa36-418c-9835-6e2f3c26c97f)

**Comment by gep13** [comment]
Do you see this going out as a 3.0.2?

**Comment by mwallner** [comment]
Yes, but this might be related/ solved together with GH-536, I'm currently investigating both issues and will keep you posted.
