### ISSUE TITLE
Web Installer and Install-BoxstarterPackage should treat .nupkg correctly

### ISSUE THREAD

**Issue by nbarnwell** [chocolatey/boxstarter#67]
Currently they both assume the file is a text file, so they read it's contents, and make it the content of a ChocolateyInstall.ps1 in a temp package, then attempt to install the temp package.

It would be better for it to detect a file is a nupkg file and install that directly (possibly by copying to the local repo and invoking standard functions from there?).

**Comment by pauby** [comment]
Why would you want to use Boxstarter to install a package .nupkg file over Chocolatey?

**Comment by pauby** [comment]
There has been no updated to this in some time so I'm going to go ahead and close it. We can always reopen it again if needed.
