### ISSUE TITLE
"Cannot find package" if using prerelease package

### ISSUE THREAD

**Issue by nbarnwell** [chocolatey/boxstarter#69]
If using a package called MyPackage.0.0.0-alpha1.nupkg, which is valid according to semver (and as supported by Nuget) the error "cannot find package" is recorded.

**Comment by pauby** [comment]
I appreciate this is some time ago but need more information on this.

Are you trying to install it via Chocolatey and it's Chocolatey throwing the error? Logs? Screenshots?

**Comment by nbarnwell** [comment]
I honestly can't remember now, I'm afraid. Four years is a long time and I haven't had the issue recently. You may as well just close this and if it happens again I'll try and put more information in when I record it.
